# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawServiceTypesClient, RawServiceTypesClient
from .types.service_type_get_v_1_response import ServiceTypeGetV1Response
from .types.service_types_list_v_1_response import ServiceTypesListV1Response


class ServiceTypesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawServiceTypesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawServiceTypesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawServiceTypesClient
        """
        return self._raw_client

    def list_service_types(
        self,
        *,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ServiceTypesListV1Response:
        """
        Parameters
        ----------
        page : typing.Optional[int]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ServiceTypesListV1Response

        Examples
        --------
        from usebridge_api import BridgeApiClient

        client = BridgeApiClient(
            api_key="YOUR_API_KEY",
        )
        client.service_types.list_service_types()
        """
        _response = self._raw_client.list_service_types(page=page, limit=limit, request_options=request_options)
        return _response.data

    def get_service_type(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ServiceTypeGetV1Response:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ServiceTypeGetV1Response

        Examples
        --------
        from usebridge_api import BridgeApiClient

        client = BridgeApiClient(
            api_key="YOUR_API_KEY",
        )
        client.service_types.get_service_type(
            id="id",
        )
        """
        _response = self._raw_client.get_service_type(id, request_options=request_options)
        return _response.data


class AsyncServiceTypesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawServiceTypesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawServiceTypesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawServiceTypesClient
        """
        return self._raw_client

    async def list_service_types(
        self,
        *,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ServiceTypesListV1Response:
        """
        Parameters
        ----------
        page : typing.Optional[int]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ServiceTypesListV1Response

        Examples
        --------
        import asyncio

        from usebridge_api import AsyncBridgeApiClient

        client = AsyncBridgeApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.service_types.list_service_types()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_service_types(page=page, limit=limit, request_options=request_options)
        return _response.data

    async def get_service_type(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ServiceTypeGetV1Response:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ServiceTypeGetV1Response

        Examples
        --------
        import asyncio

        from usebridge_api import AsyncBridgeApiClient

        client = AsyncBridgeApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.service_types.get_service_type(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_service_type(id, request_options=request_options)
        return _response.data
