# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .provider_eligibility_create_v_1_request_location_field_country import (
    ProviderEligibilityCreateV1RequestLocationFieldCountry,
)
from .provider_eligibility_create_v_1_request_location_field_state import (
    ProviderEligibilityCreateV1RequestLocationFieldState,
)


class ProviderEligibilityCreateV1RequestLocation(UniversalBaseModel):
    line_1: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="line1"), pydantic.Field(alias="line1")
    ] = None
    line_2: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="line2"), pydantic.Field(alias="line2")
    ] = None
    city: typing.Optional[str] = None
    state: ProviderEligibilityCreateV1RequestLocationFieldState = pydantic.Field()
    """
    2 letter US state code
    """

    postal_code: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="postalCode"), pydantic.Field(alias="postalCode")
    ] = None
    country: typing.Optional[ProviderEligibilityCreateV1RequestLocationFieldCountry] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
