# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .provider_eligibility_create_v_1_response_location import ProviderEligibilityCreateV1ResponseLocation
from .provider_eligibility_create_v_1_response_provider import ProviderEligibilityCreateV1ResponseProvider
from .provider_eligibility_create_v_1_response_status import ProviderEligibilityCreateV1ResponseStatus


class ProviderEligibilityCreateV1Response(UniversalBaseModel):
    id: str
    validated_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="validatedAt"),
        pydantic.Field(alias="validatedAt", description="Timestamp this was executed"),
    ]
    date_of_service: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="dateOfService"), pydantic.Field(alias="dateOfService")
    ]
    service_type_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="serviceTypeId"), pydantic.Field(alias="serviceTypeId")
    ]
    location: ProviderEligibilityCreateV1ResponseLocation
    payer_id: typing_extensions.Annotated[str, FieldMetadata(alias="payerId"), pydantic.Field(alias="payerId")]
    status: ProviderEligibilityCreateV1ResponseStatus = pydantic.Field()
    """
    The eligibility status of this check. Note, the patient may be eligible on a location/payer-basis, but providers are not available. Use a combination of this _and_ the `providers` array to determine next steps.
    """

    providers: typing.List[ProviderEligibilityCreateV1ResponseProvider]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
