# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .patient_create_v_2_request import PatientCreateV2Request
    from .patient_create_v_2_request_address import PatientCreateV2RequestAddress
    from .patient_create_v_2_request_address_field_country import PatientCreateV2RequestAddressFieldCountry
    from .patient_create_v_2_request_address_field_state import PatientCreateV2RequestAddressFieldState
    from .patient_create_v_2_request_coverage import PatientCreateV2RequestCoverage
    from .patient_create_v_2_request_metadata import PatientCreateV2RequestMetadata
    from .patient_create_v_2_response import PatientCreateV2Response
    from .patient_create_v_2_response_account import PatientCreateV2ResponseAccount
    from .patient_create_v_2_response_account_field_status import PatientCreateV2ResponseAccountFieldStatus
    from .patient_create_v_2_response_address import PatientCreateV2ResponseAddress
    from .patient_create_v_2_response_address_field_country import PatientCreateV2ResponseAddressFieldCountry
    from .patient_create_v_2_response_address_field_state import PatientCreateV2ResponseAddressFieldState
    from .patient_create_v_2_response_coverage import PatientCreateV2ResponseCoverage
    from .patient_create_v_2_response_metadata import PatientCreateV2ResponseMetadata
    from .patient_get_v_2_response import PatientGetV2Response
    from .patient_get_v_2_response_account import PatientGetV2ResponseAccount
    from .patient_get_v_2_response_account_field_status import PatientGetV2ResponseAccountFieldStatus
    from .patient_get_v_2_response_address import PatientGetV2ResponseAddress
    from .patient_get_v_2_response_address_field_country import PatientGetV2ResponseAddressFieldCountry
    from .patient_get_v_2_response_address_field_state import PatientGetV2ResponseAddressFieldState
    from .patient_get_v_2_response_coverage import PatientGetV2ResponseCoverage
    from .patient_get_v_2_response_metadata import PatientGetV2ResponseMetadata
_dynamic_imports: typing.Dict[str, str] = {
    "PatientCreateV2Request": ".patient_create_v_2_request",
    "PatientCreateV2RequestAddress": ".patient_create_v_2_request_address",
    "PatientCreateV2RequestAddressFieldCountry": ".patient_create_v_2_request_address_field_country",
    "PatientCreateV2RequestAddressFieldState": ".patient_create_v_2_request_address_field_state",
    "PatientCreateV2RequestCoverage": ".patient_create_v_2_request_coverage",
    "PatientCreateV2RequestMetadata": ".patient_create_v_2_request_metadata",
    "PatientCreateV2Response": ".patient_create_v_2_response",
    "PatientCreateV2ResponseAccount": ".patient_create_v_2_response_account",
    "PatientCreateV2ResponseAccountFieldStatus": ".patient_create_v_2_response_account_field_status",
    "PatientCreateV2ResponseAddress": ".patient_create_v_2_response_address",
    "PatientCreateV2ResponseAddressFieldCountry": ".patient_create_v_2_response_address_field_country",
    "PatientCreateV2ResponseAddressFieldState": ".patient_create_v_2_response_address_field_state",
    "PatientCreateV2ResponseCoverage": ".patient_create_v_2_response_coverage",
    "PatientCreateV2ResponseMetadata": ".patient_create_v_2_response_metadata",
    "PatientGetV2Response": ".patient_get_v_2_response",
    "PatientGetV2ResponseAccount": ".patient_get_v_2_response_account",
    "PatientGetV2ResponseAccountFieldStatus": ".patient_get_v_2_response_account_field_status",
    "PatientGetV2ResponseAddress": ".patient_get_v_2_response_address",
    "PatientGetV2ResponseAddressFieldCountry": ".patient_get_v_2_response_address_field_country",
    "PatientGetV2ResponseAddressFieldState": ".patient_get_v_2_response_address_field_state",
    "PatientGetV2ResponseCoverage": ".patient_get_v_2_response_coverage",
    "PatientGetV2ResponseMetadata": ".patient_get_v_2_response_metadata",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "PatientCreateV2Request",
    "PatientCreateV2RequestAddress",
    "PatientCreateV2RequestAddressFieldCountry",
    "PatientCreateV2RequestAddressFieldState",
    "PatientCreateV2RequestCoverage",
    "PatientCreateV2RequestMetadata",
    "PatientCreateV2Response",
    "PatientCreateV2ResponseAccount",
    "PatientCreateV2ResponseAccountFieldStatus",
    "PatientCreateV2ResponseAddress",
    "PatientCreateV2ResponseAddressFieldCountry",
    "PatientCreateV2ResponseAddressFieldState",
    "PatientCreateV2ResponseCoverage",
    "PatientCreateV2ResponseMetadata",
    "PatientGetV2Response",
    "PatientGetV2ResponseAccount",
    "PatientGetV2ResponseAccountFieldStatus",
    "PatientGetV2ResponseAddress",
    "PatientGetV2ResponseAddressFieldCountry",
    "PatientGetV2ResponseAddressFieldState",
    "PatientGetV2ResponseCoverage",
    "PatientGetV2ResponseMetadata",
]
