# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .patient_get_v_2_response_account import PatientGetV2ResponseAccount
from .patient_get_v_2_response_address import PatientGetV2ResponseAddress
from .patient_get_v_2_response_coverage import PatientGetV2ResponseCoverage
from .patient_get_v_2_response_metadata import PatientGetV2ResponseMetadata


class PatientGetV2Response(UniversalBaseModel):
    id: str
    patient_token: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="patientToken"), pydantic.Field(alias="patientToken")
    ] = None
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]
    external_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="externalId"), pydantic.Field(alias="externalId")
    ] = None
    coverage: typing.List[PatientGetV2ResponseCoverage]
    first_name: typing_extensions.Annotated[str, FieldMetadata(alias="firstName"), pydantic.Field(alias="firstName")]
    last_name: typing_extensions.Annotated[str, FieldMetadata(alias="lastName"), pydantic.Field(alias="lastName")]
    date_of_birth: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="dateOfBirth"), pydantic.Field(alias="dateOfBirth")
    ]
    email: str
    phone: typing.Optional[str] = None
    address: typing.Optional[PatientGetV2ResponseAddress] = None
    metadata: typing.Optional[PatientGetV2ResponseMetadata] = pydantic.Field(default=None)
    """
    Customizable object of string to string key-value data
    """

    account: typing.Optional[PatientGetV2ResponseAccount] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
