# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawServiceEligibilityClient, RawServiceEligibilityClient
from .types.service_eligibility_get_v_1_response import ServiceEligibilityGetV1Response
from .types.service_eligibility_stream_v_1_response import ServiceEligibilityStreamV1Response

if typing.TYPE_CHECKING:
    from .v_2.client import AsyncV2Client, V2Client


class ServiceEligibilityClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawServiceEligibilityClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._v_2: typing.Optional[V2Client] = None

    @property
    def with_raw_response(self) -> RawServiceEligibilityClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawServiceEligibilityClient
        """
        return self._raw_client

    def stream_service_eligibility(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Iterator[ServiceEligibilityStreamV1Response]:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.Iterator[ServiceEligibilityStreamV1Response]

        Examples
        --------
        from rtaylor_205 import BridgeApiClient

        client = BridgeApiClient(
            api_key="YOUR_API_KEY",
        )
        response = client.service_eligibility.stream_service_eligibility(
            id="id",
        )
        for chunk in response:
            yield chunk
        """
        with self._raw_client.stream_service_eligibility(id, request_options=request_options) as r:
            yield from r.data

    def get_service_eligibility(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ServiceEligibilityGetV1Response:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ServiceEligibilityGetV1Response

        Examples
        --------
        from rtaylor_205 import BridgeApiClient

        client = BridgeApiClient(
            api_key="YOUR_API_KEY",
        )
        client.service_eligibility.get_service_eligibility(
            id="id",
        )
        """
        _response = self._raw_client.get_service_eligibility(id, request_options=request_options)
        return _response.data

    @property
    def v_2(self):
        if self._v_2 is None:
            from .v_2.client import V2Client  # noqa: E402

            self._v_2 = V2Client(client_wrapper=self._client_wrapper)
        return self._v_2


class AsyncServiceEligibilityClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawServiceEligibilityClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._v_2: typing.Optional[AsyncV2Client] = None

    @property
    def with_raw_response(self) -> AsyncRawServiceEligibilityClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawServiceEligibilityClient
        """
        return self._raw_client

    async def stream_service_eligibility(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.AsyncIterator[ServiceEligibilityStreamV1Response]:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.AsyncIterator[ServiceEligibilityStreamV1Response]

        Examples
        --------
        import asyncio

        from rtaylor_205 import AsyncBridgeApiClient

        client = AsyncBridgeApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.service_eligibility.stream_service_eligibility(
                id="id",
            )
            async for chunk in response:
                yield chunk


        asyncio.run(main())
        """
        async with self._raw_client.stream_service_eligibility(id, request_options=request_options) as r:
            async for _chunk in r.data:
                yield _chunk

    async def get_service_eligibility(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ServiceEligibilityGetV1Response:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ServiceEligibilityGetV1Response

        Examples
        --------
        import asyncio

        from rtaylor_205 import AsyncBridgeApiClient

        client = AsyncBridgeApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.service_eligibility.get_service_eligibility(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_service_eligibility(id, request_options=request_options)
        return _response.data

    @property
    def v_2(self):
        if self._v_2 is None:
            from .v_2.client import AsyncV2Client  # noqa: E402

            self._v_2 = AsyncV2Client(client_wrapper=self._client_wrapper)
        return self._v_2
