# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .service_eligibility_get_v_1_response_clinical_info import ServiceEligibilityGetV1ResponseClinicalInfo
from .service_eligibility_get_v_1_response_conditional_patient_responsibility import (
    ServiceEligibilityGetV1ResponseConditionalPatientResponsibility,
)
from .service_eligibility_get_v_1_response_message import ServiceEligibilityGetV1ResponseMessage
from .service_eligibility_get_v_1_response_patient_responsibility import (
    ServiceEligibilityGetV1ResponsePatientResponsibility,
)
from .service_eligibility_get_v_1_response_policy_id import ServiceEligibilityGetV1ResponsePolicyId
from .service_eligibility_get_v_1_response_provider import ServiceEligibilityGetV1ResponseProvider
from .service_eligibility_get_v_1_response_state import ServiceEligibilityGetV1ResponseState
from .service_eligibility_get_v_1_response_status import ServiceEligibilityGetV1ResponseStatus


class ServiceEligibilityGetV1Response(UniversalBaseModel):
    id: str
    organization_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="organizationId"), pydantic.Field(alias="organizationId")
    ]
    validated_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="validatedAt"),
        pydantic.Field(alias="validatedAt", description="Timestamp this was executed"),
    ] = None
    service_type_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="serviceTypeId"), pydantic.Field(alias="serviceTypeId")
    ]
    date_of_service: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="dateOfService"), pydantic.Field(alias="dateOfService")
    ]
    status: ServiceEligibilityGetV1ResponseStatus
    patient_responsibility: typing_extensions.Annotated[
        typing.Optional[ServiceEligibilityGetV1ResponsePatientResponsibility],
        FieldMetadata(alias="patientResponsibility"),
        pydantic.Field(
            alias="patientResponsibility",
            description="Describes the Patient Responsibility. All dollar values are in USD cents ($15 = 1500). The 'total' is the amount that the patient owes. The breakdown are in non-oop fields. The oop fields apply when the patient has hit (or will hit) their OOP limits.",
        ),
    ] = None
    providers: typing.List[ServiceEligibilityGetV1ResponseProvider]
    policy_ids: typing_extensions.Annotated[
        typing.List[ServiceEligibilityGetV1ResponsePolicyId],
        FieldMetadata(alias="policyIds"),
        pydantic.Field(alias="policyIds"),
    ]
    state: ServiceEligibilityGetV1ResponseState = pydantic.Field()
    """
    2 letter US state code
    """

    messages: typing.Optional[typing.List[ServiceEligibilityGetV1ResponseMessage]] = None
    clinical_info: typing_extensions.Annotated[
        typing.Optional[ServiceEligibilityGetV1ResponseClinicalInfo],
        FieldMetadata(alias="clinicalInfo"),
        pydantic.Field(alias="clinicalInfo"),
    ] = None
    conditional_patient_responsibilities: typing_extensions.Annotated[
        typing.Optional[typing.List[ServiceEligibilityGetV1ResponseConditionalPatientResponsibility]],
        FieldMetadata(alias="conditionalPatientResponsibilities"),
        pydantic.Field(alias="conditionalPatientResponsibilities"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
