# This file was auto-generated by Fern from our API Definition.

import typing

ServiceEligibilityGetV1ResponseConditionalPatientResponsibilitiesElementLimitFieldMetric = typing.Union[
    typing.Literal["VISIT", "UNITS"], typing.Any
]
