# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .service_eligibility_stream_v_1_response_clinical_info_field_diagnosis import (
    ServiceEligibilityStreamV1ResponseClinicalInfoFieldDiagnosis,
)


class ServiceEligibilityStreamV1ResponseClinicalInfo(UniversalBaseModel):
    diagnoses: typing.Optional[typing.List[ServiceEligibilityStreamV1ResponseClinicalInfoFieldDiagnosis]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
