# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .service_eligibility_stream_v_1_response_conditional_patient_responsibilities_element_limit_field_metric import (
    ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementLimitFieldMetric,
)
from .service_eligibility_stream_v_1_response_conditional_patient_responsibilities_element_limit_field_period import (
    ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementLimitFieldPeriod,
)
from .service_eligibility_stream_v_1_response_conditional_patient_responsibilities_element_limit_field_type import (
    ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementLimitFieldType,
)
from .service_eligibility_stream_v_1_response_conditional_patient_responsibilities_element_limit_field_units import (
    ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementLimitFieldUnits,
)


class ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementLimit(UniversalBaseModel):
    type: ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementLimitFieldType
    value: typing.Optional[int] = None
    metric: typing.Optional[
        ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementLimitFieldMetric
    ] = None
    period: typing.Optional[
        ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementLimitFieldPeriod
    ] = None
    units: typing.Optional[
        ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementLimitFieldUnits
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
