# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .policy_create_v_2_request_person import PolicyCreateV2RequestPerson
from .policy_create_v_2_request_state import PolicyCreateV2RequestState


class PolicyCreateV2Request(UniversalBaseModel):
    external_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="externalId"),
        pydantic.Field(alias="externalId", description="Optional unique identifier"),
    ] = None
    person: PolicyCreateV2RequestPerson
    state: PolicyCreateV2RequestState = pydantic.Field()
    """
    2 letter US state code
    """

    payer_id: typing_extensions.Annotated[str, FieldMetadata(alias="payerId"), pydantic.Field(alias="payerId")]
    member_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="memberId"), pydantic.Field(alias="memberId")
    ] = None
    date_of_service: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="dateOfService"),
        pydantic.Field(alias="dateOfService", description="Full ISO8601 timestamp, including timezone"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
