# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .policy_create_v_2_response_error import PolicyCreateV2ResponseError
from .policy_create_v_2_response_latest import PolicyCreateV2ResponseLatest
from .policy_create_v_2_response_payer import PolicyCreateV2ResponsePayer
from .policy_create_v_2_response_person import PolicyCreateV2ResponsePerson
from .policy_create_v_2_response_policy_holder import PolicyCreateV2ResponsePolicyHolder
from .policy_create_v_2_response_relationship import PolicyCreateV2ResponseRelationship
from .policy_create_v_2_response_state import PolicyCreateV2ResponseState
from .policy_create_v_2_response_status import PolicyCreateV2ResponseStatus


class PolicyCreateV2Response(UniversalBaseModel):
    id: str
    external_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="externalId"), pydantic.Field(alias="externalId")
    ] = None
    payer_id: typing_extensions.Annotated[str, FieldMetadata(alias="payerId"), pydantic.Field(alias="payerId")]
    plan_name: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="planName"), pydantic.Field(alias="planName")
    ] = None
    payer: PolicyCreateV2ResponsePayer
    person: typing.Optional[PolicyCreateV2ResponsePerson] = None
    status: PolicyCreateV2ResponseStatus
    errors: typing.Optional[typing.List[PolicyCreateV2ResponseError]] = None
    member_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="memberId"), pydantic.Field(alias="memberId")
    ] = None
    policy_holder: typing_extensions.Annotated[
        typing.Optional[PolicyCreateV2ResponsePolicyHolder],
        FieldMetadata(alias="policyHolder"),
        pydantic.Field(alias="policyHolder"),
    ] = None
    relationship: typing.Optional[PolicyCreateV2ResponseRelationship] = None
    state: PolicyCreateV2ResponseState = pydantic.Field()
    """
    2 letter US state code
    """

    patient_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="patientId"), pydantic.Field(alias="patientId")
    ] = None
    latest: typing.Optional[PolicyCreateV2ResponseLatest] = None
    token: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="_token"),
        pydantic.Field(alias="_token", description="Temporary access token to retrieve this Policy"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
