# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        ProviderEligibilityCreateV1Request,
        ProviderEligibilityCreateV1RequestLocation,
        ProviderEligibilityCreateV1RequestLocationFieldCountry,
        ProviderEligibilityCreateV1RequestLocationFieldState,
        ProviderEligibilityCreateV1Response,
        ProviderEligibilityCreateV1ResponseLocation,
        ProviderEligibilityCreateV1ResponseLocationFieldCountry,
        ProviderEligibilityCreateV1ResponseLocationFieldState,
        ProviderEligibilityCreateV1ResponseProvider,
        ProviderEligibilityCreateV1ResponseProvidersElementType,
        ProviderEligibilityCreateV1ResponseStatus,
        ProviderEligibilityGetV1Response,
        ProviderEligibilityGetV1ResponseLocation,
        ProviderEligibilityGetV1ResponseLocationFieldCountry,
        ProviderEligibilityGetV1ResponseLocationFieldState,
        ProviderEligibilityGetV1ResponseProvider,
        ProviderEligibilityGetV1ResponseProvidersElementType,
        ProviderEligibilityGetV1ResponseStatus,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "ProviderEligibilityCreateV1Request": ".types",
    "ProviderEligibilityCreateV1RequestLocation": ".types",
    "ProviderEligibilityCreateV1RequestLocationFieldCountry": ".types",
    "ProviderEligibilityCreateV1RequestLocationFieldState": ".types",
    "ProviderEligibilityCreateV1Response": ".types",
    "ProviderEligibilityCreateV1ResponseLocation": ".types",
    "ProviderEligibilityCreateV1ResponseLocationFieldCountry": ".types",
    "ProviderEligibilityCreateV1ResponseLocationFieldState": ".types",
    "ProviderEligibilityCreateV1ResponseProvider": ".types",
    "ProviderEligibilityCreateV1ResponseProvidersElementType": ".types",
    "ProviderEligibilityCreateV1ResponseStatus": ".types",
    "ProviderEligibilityGetV1Response": ".types",
    "ProviderEligibilityGetV1ResponseLocation": ".types",
    "ProviderEligibilityGetV1ResponseLocationFieldCountry": ".types",
    "ProviderEligibilityGetV1ResponseLocationFieldState": ".types",
    "ProviderEligibilityGetV1ResponseProvider": ".types",
    "ProviderEligibilityGetV1ResponseProvidersElementType": ".types",
    "ProviderEligibilityGetV1ResponseStatus": ".types",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ProviderEligibilityCreateV1Request",
    "ProviderEligibilityCreateV1RequestLocation",
    "ProviderEligibilityCreateV1RequestLocationFieldCountry",
    "ProviderEligibilityCreateV1RequestLocationFieldState",
    "ProviderEligibilityCreateV1Response",
    "ProviderEligibilityCreateV1ResponseLocation",
    "ProviderEligibilityCreateV1ResponseLocationFieldCountry",
    "ProviderEligibilityCreateV1ResponseLocationFieldState",
    "ProviderEligibilityCreateV1ResponseProvider",
    "ProviderEligibilityCreateV1ResponseProvidersElementType",
    "ProviderEligibilityCreateV1ResponseStatus",
    "ProviderEligibilityGetV1Response",
    "ProviderEligibilityGetV1ResponseLocation",
    "ProviderEligibilityGetV1ResponseLocationFieldCountry",
    "ProviderEligibilityGetV1ResponseLocationFieldState",
    "ProviderEligibilityGetV1ResponseProvider",
    "ProviderEligibilityGetV1ResponseProvidersElementType",
    "ProviderEligibilityGetV1ResponseStatus",
]
