# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .service_type_get_v_1_response import ServiceTypeGetV1Response
    from .service_type_get_v_1_response_note_field import ServiceTypeGetV1ResponseNoteField
    from .service_type_get_v_1_response_place_of_service import ServiceTypeGetV1ResponsePlaceOfService
    from .service_type_get_v_1_response_provider_type import ServiceTypeGetV1ResponseProviderType
    from .service_type_get_v_1_response_provider_types_element import ServiceTypeGetV1ResponseProviderTypesElement
    from .service_types_list_v_1_response import ServiceTypesListV1Response
    from .service_types_list_v_1_response_item import ServiceTypesListV1ResponseItem
    from .service_types_list_v_1_response_item_note_field import ServiceTypesListV1ResponseItemNoteField
    from .service_types_list_v_1_response_item_place_of_service import ServiceTypesListV1ResponseItemPlaceOfService
    from .service_types_list_v_1_response_item_provider_type import ServiceTypesListV1ResponseItemProviderType
    from .service_types_list_v_1_response_item_provider_types_element import (
        ServiceTypesListV1ResponseItemProviderTypesElement,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "ServiceTypeGetV1Response": ".service_type_get_v_1_response",
    "ServiceTypeGetV1ResponseNoteField": ".service_type_get_v_1_response_note_field",
    "ServiceTypeGetV1ResponsePlaceOfService": ".service_type_get_v_1_response_place_of_service",
    "ServiceTypeGetV1ResponseProviderType": ".service_type_get_v_1_response_provider_type",
    "ServiceTypeGetV1ResponseProviderTypesElement": ".service_type_get_v_1_response_provider_types_element",
    "ServiceTypesListV1Response": ".service_types_list_v_1_response",
    "ServiceTypesListV1ResponseItem": ".service_types_list_v_1_response_item",
    "ServiceTypesListV1ResponseItemNoteField": ".service_types_list_v_1_response_item_note_field",
    "ServiceTypesListV1ResponseItemPlaceOfService": ".service_types_list_v_1_response_item_place_of_service",
    "ServiceTypesListV1ResponseItemProviderType": ".service_types_list_v_1_response_item_provider_type",
    "ServiceTypesListV1ResponseItemProviderTypesElement": ".service_types_list_v_1_response_item_provider_types_element",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ServiceTypeGetV1Response",
    "ServiceTypeGetV1ResponseNoteField",
    "ServiceTypeGetV1ResponsePlaceOfService",
    "ServiceTypeGetV1ResponseProviderType",
    "ServiceTypeGetV1ResponseProviderTypesElement",
    "ServiceTypesListV1Response",
    "ServiceTypesListV1ResponseItem",
    "ServiceTypesListV1ResponseItemNoteField",
    "ServiceTypesListV1ResponseItemPlaceOfService",
    "ServiceTypesListV1ResponseItemProviderType",
    "ServiceTypesListV1ResponseItemProviderTypesElement",
]
