# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .note_create_v_1_response_addenda_element_signature_field_provider import (
    NoteCreateV1ResponseAddendaElementSignatureFieldProvider,
)


class NoteCreateV1ResponseAddendaElementSignature(UniversalBaseModel):
    timestamp: dt.datetime
    provider: NoteCreateV1ResponseAddendaElementSignatureFieldProvider

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
