# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .note_addendum_create_v_1_request_data import NoteAddendumCreateV1RequestData
from .note_addendum_create_v_1_request_signature import NoteAddendumCreateV1RequestSignature


class NoteAddendumCreateV1Request(UniversalBaseModel):
    external_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="externalId"), pydantic.Field(alias="externalId")
    ] = None
    data: NoteAddendumCreateV1RequestData
    signature: NoteAddendumCreateV1RequestSignature

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
