# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        EstimateChargeAuthorizeStripeV1Response,
        EstimateChargeAuthorizeStripeV1ResponseStatus,
        EstimateChargeAuthorizeStripeV1ResponseStripe,
        EstimateChargeCancelStripeV1Response,
        EstimateChargeCancelStripeV1ResponseStatus,
        EstimateChargeCancelStripeV1ResponseStripe,
        EstimateChargeCaptureStripeV1Response,
        EstimateChargeCaptureStripeV1ResponseStatus,
        EstimateChargeCaptureStripeV1ResponseStripe,
        EstimateChargeCreateV1Request,
        EstimateChargeCreateV1Response,
        EstimateChargeCreateV1ResponseStatus,
        EstimateChargeRefundStripeV1Response,
        EstimateChargeRefundStripeV1ResponseStatus,
        EstimateChargeRefundStripeV1ResponseStripe,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "EstimateChargeAuthorizeStripeV1Response": ".types",
    "EstimateChargeAuthorizeStripeV1ResponseStatus": ".types",
    "EstimateChargeAuthorizeStripeV1ResponseStripe": ".types",
    "EstimateChargeCancelStripeV1Response": ".types",
    "EstimateChargeCancelStripeV1ResponseStatus": ".types",
    "EstimateChargeCancelStripeV1ResponseStripe": ".types",
    "EstimateChargeCaptureStripeV1Response": ".types",
    "EstimateChargeCaptureStripeV1ResponseStatus": ".types",
    "EstimateChargeCaptureStripeV1ResponseStripe": ".types",
    "EstimateChargeCreateV1Request": ".types",
    "EstimateChargeCreateV1Response": ".types",
    "EstimateChargeCreateV1ResponseStatus": ".types",
    "EstimateChargeRefundStripeV1Response": ".types",
    "EstimateChargeRefundStripeV1ResponseStatus": ".types",
    "EstimateChargeRefundStripeV1ResponseStripe": ".types",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "EstimateChargeAuthorizeStripeV1Response",
    "EstimateChargeAuthorizeStripeV1ResponseStatus",
    "EstimateChargeAuthorizeStripeV1ResponseStripe",
    "EstimateChargeCancelStripeV1Response",
    "EstimateChargeCancelStripeV1ResponseStatus",
    "EstimateChargeCancelStripeV1ResponseStripe",
    "EstimateChargeCaptureStripeV1Response",
    "EstimateChargeCaptureStripeV1ResponseStatus",
    "EstimateChargeCaptureStripeV1ResponseStripe",
    "EstimateChargeCreateV1Request",
    "EstimateChargeCreateV1Response",
    "EstimateChargeCreateV1ResponseStatus",
    "EstimateChargeRefundStripeV1Response",
    "EstimateChargeRefundStripeV1ResponseStatus",
    "EstimateChargeRefundStripeV1ResponseStripe",
]
