# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ...core.api_error import ApiError
from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.http_response import AsyncHttpResponse, HttpResponse
from ...core.jsonable_encoder import encode_path_param
from ...core.parse_error import ParsingError
from ...core.pydantic_utilities import parse_obj_as
from ...core.request_options import RequestOptions
from .types.estimate_charge_authorize_stripe_v_1_response import EstimateChargeAuthorizeStripeV1Response
from .types.estimate_charge_cancel_stripe_v_1_response import EstimateChargeCancelStripeV1Response
from .types.estimate_charge_capture_stripe_v_1_response import EstimateChargeCaptureStripeV1Response
from .types.estimate_charge_create_v_1_response import EstimateChargeCreateV1Response
from .types.estimate_charge_refund_stripe_v_1_response import EstimateChargeRefundStripeV1Response
from .types.estimate_charges_list_v_1_filter_status import EstimateChargesListV1FilterStatus
from .types.estimate_charges_list_v_1_response import EstimateChargesListV1Response
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawEstimateChargesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_estimate_charges(
        self,
        *,
        filter_patient_id: typing.Optional[str] = None,
        filter_service_id: typing.Optional[str] = None,
        filter_service_eligibility_id: typing.Optional[str] = None,
        filter_status: typing.Optional[EstimateChargesListV1FilterStatus] = None,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[EstimateChargesListV1Response]:
        """
        Parameters
        ----------
        filter_patient_id : typing.Optional[str]
            should be JSON-encoded, for example filter.patientId="pat_xxx"

        filter_service_id : typing.Optional[str]
            should be JSON-encoded, for example filter.serviceId="svc_xxx"

        filter_service_eligibility_id : typing.Optional[str]
            should be JSON-encoded, for example filter.serviceEligibilityId="sel_xxx"

        filter_status : typing.Optional[EstimateChargesListV1FilterStatus]
            should be JSON-encoded, for example filter.status="AUTHORIZED"

        page : typing.Optional[int]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[EstimateChargesListV1Response]
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/estimate-charges",
            method="GET",
            params={
                "filter.patientId": filter_patient_id,
                "filter.serviceId": filter_service_id,
                "filter.serviceEligibilityId": filter_service_eligibility_id,
                "filter.status": filter_status,
                "page": page,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EstimateChargesListV1Response,
                    parse_obj_as(
                        type_=EstimateChargesListV1Response,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_estimate_charge(
        self,
        *,
        patient_id: str,
        service_eligibility_id: str,
        external_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[EstimateChargeCreateV1Response]:
        """
        This endpoint can only be used after setting up the billing integration. Refer to the [billing integration documentation](/documentation/integrations/billing/overview) for more details.

        This endpoint may return a `409` error response with one of these public `message` values:
        - `Conflicting EstimateCharge exists`
        - `Missing Service Eligibility Amount`

        Parameters
        ----------
        patient_id : str

        service_eligibility_id : str

        external_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[EstimateChargeCreateV1Response]
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/estimate-charges",
            method="POST",
            json={
                "patientId": patient_id,
                "serviceEligibilityId": service_eligibility_id,
                "externalId": external_id,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EstimateChargeCreateV1Response,
                    parse_obj_as(
                        type_=EstimateChargeCreateV1Response,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def authorize_stripe_estimate_charge(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[EstimateChargeAuthorizeStripeV1Response]:
        """
        This endpoint can only be used after setting up the billing integration. Refer to the [billing integration documentation](/documentation/integrations/billing/overview) for more details.

        This endpoint may return a `409` error response with one of these public `message` values:
        - `Invalid Estimate Charge Status`
        - `Missing Customer`
        - `Missing Customer Payment Method`
        - `Payment Already Captured`
        - `Payment has been Voided`

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[EstimateChargeAuthorizeStripeV1Response]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/estimate-charges/{encode_path_param(id)}/authorize/stripe",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EstimateChargeAuthorizeStripeV1Response,
                    parse_obj_as(
                        type_=EstimateChargeAuthorizeStripeV1Response,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def capture_stripe_estimate_charge(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[EstimateChargeCaptureStripeV1Response]:
        """
        This endpoint can only be used after setting up the billing integration. Refer to the [billing integration documentation](/documentation/integrations/billing/overview) for more details.

        This endpoint may return a `409` error response with one of these public `message` values:
        - `Invalid Estimate Charge Status`
        - `Missing Customer`
        - `Missing Customer Payment Method`
        - `Payment Already Captured`
        - `Payment has been Voided`

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[EstimateChargeCaptureStripeV1Response]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/estimate-charges/{encode_path_param(id)}/capture/stripe",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EstimateChargeCaptureStripeV1Response,
                    parse_obj_as(
                        type_=EstimateChargeCaptureStripeV1Response,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def refund_stripe_estimate_charge(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[EstimateChargeRefundStripeV1Response]:
        """
        This endpoint can only be used after setting up the billing integration. Refer to the [billing integration documentation](/documentation/integrations/billing/overview) for more details.

        This endpoint may return a `409` error response with one of these public `message` values:
        - `Invalid Estimate Charge Status`
        - `Missing Captured Transaction`
        - `Missing Customer`
        - `Missing Payment Intent`

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[EstimateChargeRefundStripeV1Response]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/estimate-charges/{encode_path_param(id)}/refund/stripe",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EstimateChargeRefundStripeV1Response,
                    parse_obj_as(
                        type_=EstimateChargeRefundStripeV1Response,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def cancel_stripe_estimate_charge(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[EstimateChargeCancelStripeV1Response]:
        """
        This endpoint can only be used after setting up the billing integration. Refer to the [billing integration documentation](/documentation/integrations/billing/overview) for more details.

        This endpoint may return a `409` error response with one of these public `message` values:
        - `Invalid Estimate Charge Status`
        - `Missing Authorized Transaction`
        - `Missing Customer`
        - `Missing Payment Intent`
        - `Payment Already Captured`

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[EstimateChargeCancelStripeV1Response]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/estimate-charges/{encode_path_param(id)}/cancel/stripe",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EstimateChargeCancelStripeV1Response,
                    parse_obj_as(
                        type_=EstimateChargeCancelStripeV1Response,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawEstimateChargesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_estimate_charges(
        self,
        *,
        filter_patient_id: typing.Optional[str] = None,
        filter_service_id: typing.Optional[str] = None,
        filter_service_eligibility_id: typing.Optional[str] = None,
        filter_status: typing.Optional[EstimateChargesListV1FilterStatus] = None,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[EstimateChargesListV1Response]:
        """
        Parameters
        ----------
        filter_patient_id : typing.Optional[str]
            should be JSON-encoded, for example filter.patientId="pat_xxx"

        filter_service_id : typing.Optional[str]
            should be JSON-encoded, for example filter.serviceId="svc_xxx"

        filter_service_eligibility_id : typing.Optional[str]
            should be JSON-encoded, for example filter.serviceEligibilityId="sel_xxx"

        filter_status : typing.Optional[EstimateChargesListV1FilterStatus]
            should be JSON-encoded, for example filter.status="AUTHORIZED"

        page : typing.Optional[int]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[EstimateChargesListV1Response]
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/estimate-charges",
            method="GET",
            params={
                "filter.patientId": filter_patient_id,
                "filter.serviceId": filter_service_id,
                "filter.serviceEligibilityId": filter_service_eligibility_id,
                "filter.status": filter_status,
                "page": page,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EstimateChargesListV1Response,
                    parse_obj_as(
                        type_=EstimateChargesListV1Response,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_estimate_charge(
        self,
        *,
        patient_id: str,
        service_eligibility_id: str,
        external_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[EstimateChargeCreateV1Response]:
        """
        This endpoint can only be used after setting up the billing integration. Refer to the [billing integration documentation](/documentation/integrations/billing/overview) for more details.

        This endpoint may return a `409` error response with one of these public `message` values:
        - `Conflicting EstimateCharge exists`
        - `Missing Service Eligibility Amount`

        Parameters
        ----------
        patient_id : str

        service_eligibility_id : str

        external_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[EstimateChargeCreateV1Response]
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/estimate-charges",
            method="POST",
            json={
                "patientId": patient_id,
                "serviceEligibilityId": service_eligibility_id,
                "externalId": external_id,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EstimateChargeCreateV1Response,
                    parse_obj_as(
                        type_=EstimateChargeCreateV1Response,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def authorize_stripe_estimate_charge(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[EstimateChargeAuthorizeStripeV1Response]:
        """
        This endpoint can only be used after setting up the billing integration. Refer to the [billing integration documentation](/documentation/integrations/billing/overview) for more details.

        This endpoint may return a `409` error response with one of these public `message` values:
        - `Invalid Estimate Charge Status`
        - `Missing Customer`
        - `Missing Customer Payment Method`
        - `Payment Already Captured`
        - `Payment has been Voided`

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[EstimateChargeAuthorizeStripeV1Response]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/estimate-charges/{encode_path_param(id)}/authorize/stripe",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EstimateChargeAuthorizeStripeV1Response,
                    parse_obj_as(
                        type_=EstimateChargeAuthorizeStripeV1Response,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def capture_stripe_estimate_charge(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[EstimateChargeCaptureStripeV1Response]:
        """
        This endpoint can only be used after setting up the billing integration. Refer to the [billing integration documentation](/documentation/integrations/billing/overview) for more details.

        This endpoint may return a `409` error response with one of these public `message` values:
        - `Invalid Estimate Charge Status`
        - `Missing Customer`
        - `Missing Customer Payment Method`
        - `Payment Already Captured`
        - `Payment has been Voided`

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[EstimateChargeCaptureStripeV1Response]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/estimate-charges/{encode_path_param(id)}/capture/stripe",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EstimateChargeCaptureStripeV1Response,
                    parse_obj_as(
                        type_=EstimateChargeCaptureStripeV1Response,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def refund_stripe_estimate_charge(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[EstimateChargeRefundStripeV1Response]:
        """
        This endpoint can only be used after setting up the billing integration. Refer to the [billing integration documentation](/documentation/integrations/billing/overview) for more details.

        This endpoint may return a `409` error response with one of these public `message` values:
        - `Invalid Estimate Charge Status`
        - `Missing Captured Transaction`
        - `Missing Customer`
        - `Missing Payment Intent`

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[EstimateChargeRefundStripeV1Response]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/estimate-charges/{encode_path_param(id)}/refund/stripe",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EstimateChargeRefundStripeV1Response,
                    parse_obj_as(
                        type_=EstimateChargeRefundStripeV1Response,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def cancel_stripe_estimate_charge(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[EstimateChargeCancelStripeV1Response]:
        """
        This endpoint can only be used after setting up the billing integration. Refer to the [billing integration documentation](/documentation/integrations/billing/overview) for more details.

        This endpoint may return a `409` error response with one of these public `message` values:
        - `Invalid Estimate Charge Status`
        - `Missing Authorized Transaction`
        - `Missing Customer`
        - `Missing Payment Intent`
        - `Payment Already Captured`

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[EstimateChargeCancelStripeV1Response]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/estimate-charges/{encode_path_param(id)}/cancel/stripe",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EstimateChargeCancelStripeV1Response,
                    parse_obj_as(
                        type_=EstimateChargeCancelStripeV1Response,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
