# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .provider_enrollment_status_get_v_1_response_payer_groups_value_states import (
    ProviderEnrollmentStatusGetV1ResponsePayerGroupsValueStates,
)


class ProviderEnrollmentStatusGetV1ResponsePayerGroups(UniversalBaseModel):
    name: str
    states: typing.Dict[str, ProviderEnrollmentStatusGetV1ResponsePayerGroupsValueStates] = pydantic.Field()
    """
    Map of relevant US state codes, to enrollment status
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
