# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .provider_enrollment_status_get_v_1_response_payer_groups import ProviderEnrollmentStatusGetV1ResponsePayerGroups


class ProviderEnrollmentStatusGetV1Response(UniversalBaseModel):
    credentialing_approved: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="credentialingApproved"),
        pydantic.Field(
            alias="credentialingApproved", description="Whether initial credentialing has been completed and approved"
        ),
    ]
    payer_groups: typing_extensions.Annotated[
        typing.Dict[str, ProviderEnrollmentStatusGetV1ResponsePayerGroups],
        FieldMetadata(alias="payerGroups"),
        pydantic.Field(alias="payerGroups", description="Map of Payer Group slugs to enrollment status"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
