# This file was auto-generated by Fern from our API Definition.

import typing

ProviderEnrollmentStatusGetV1ResponsePayerGroupsValueStatesValueLinesOfBusinessFieldCommercialFieldStatus = (
    typing.Union[typing.Literal["PENDING", "SUBMITTED", "APPROVED", "ACTIVE", "DENIED", "NOT_APPLICABLE"], typing.Any]
)
