# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .provider_enrollment_status_get_v_1_response_payer_groups_value_states_value_lines_of_business_field_commercial import (
    ProviderEnrollmentStatusGetV1ResponsePayerGroupsValueStatesValueLinesOfBusinessFieldCommercial,
)
from .provider_enrollment_status_get_v_1_response_payer_groups_value_states_value_lines_of_business_field_medicare_advantage import (
    ProviderEnrollmentStatusGetV1ResponsePayerGroupsValueStatesValueLinesOfBusinessFieldMedicareAdvantage,
)


class ProviderEnrollmentStatusGetV1ResponsePayerGroupsValueStatesValueLinesOfBusiness(UniversalBaseModel):
    commercial: typing_extensions.Annotated[
        typing.Optional[ProviderEnrollmentStatusGetV1ResponsePayerGroupsValueStatesValueLinesOfBusinessFieldCommercial],
        FieldMetadata(alias="COMMERCIAL"),
        pydantic.Field(alias="COMMERCIAL"),
    ] = None
    medicare_advantage: typing_extensions.Annotated[
        typing.Optional[
            ProviderEnrollmentStatusGetV1ResponsePayerGroupsValueStatesValueLinesOfBusinessFieldMedicareAdvantage
        ],
        FieldMetadata(alias="MEDICARE_ADVANTAGE"),
        pydantic.Field(alias="MEDICARE_ADVANTAGE"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
