# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from .raw_client import AsyncRawV2Client, RawV2Client
from .types.service_eligibility_create_v_2_request_clinical_info import ServiceEligibilityCreateV2RequestClinicalInfo
from .types.service_eligibility_create_v_2_request_policy_id import ServiceEligibilityCreateV2RequestPolicyId
from .types.service_eligibility_create_v_2_request_state import ServiceEligibilityCreateV2RequestState
from .types.service_eligibility_create_v_2_response import ServiceEligibilityCreateV2Response

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class V2Client:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawV2Client(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawV2Client:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawV2Client
        """
        return self._raw_client

    def create_service_eligibility(
        self,
        *,
        service_type_id: str,
        date_of_service: dt.datetime,
        state: ServiceEligibilityCreateV2RequestState,
        policy_ids: typing.Optional[typing.Sequence[ServiceEligibilityCreateV2RequestPolicyId]] = OMIT,
        clinical_info: typing.Optional[ServiceEligibilityCreateV2RequestClinicalInfo] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ServiceEligibilityCreateV2Response:
        """
        Creates a ServiceEligibility, returns immediately in the `PENDING` status.

        Parameters
        ----------
        service_type_id : str

        date_of_service : dt.datetime
            Full ISO8601 timestamp, including timezone

        state : ServiceEligibilityCreateV2RequestState
            2 letter US state code

        policy_ids : typing.Optional[typing.Sequence[ServiceEligibilityCreateV2RequestPolicyId]]
            Optional for cash-pay ServiceTypes; omit or pass [] when no policy is available

        clinical_info : typing.Optional[ServiceEligibilityCreateV2RequestClinicalInfo]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ServiceEligibilityCreateV2Response

        Examples
        --------
        import datetime

        from rtaylor_205 import BridgeApiClient

        client = BridgeApiClient(
            api_key="YOUR_API_KEY",
        )
        client.service_eligibility.v_2.create_service_eligibility(
            service_type_id="serviceTypeId",
            date_of_service=datetime.datetime.fromisoformat(
                "2024-01-15 09:30:00+00:00",
            ),
            state="AL",
        )
        """
        _response = self._raw_client.create_service_eligibility(
            service_type_id=service_type_id,
            date_of_service=date_of_service,
            state=state,
            policy_ids=policy_ids,
            clinical_info=clinical_info,
            request_options=request_options,
        )
        return _response.data


class AsyncV2Client:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawV2Client(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawV2Client:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawV2Client
        """
        return self._raw_client

    async def create_service_eligibility(
        self,
        *,
        service_type_id: str,
        date_of_service: dt.datetime,
        state: ServiceEligibilityCreateV2RequestState,
        policy_ids: typing.Optional[typing.Sequence[ServiceEligibilityCreateV2RequestPolicyId]] = OMIT,
        clinical_info: typing.Optional[ServiceEligibilityCreateV2RequestClinicalInfo] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ServiceEligibilityCreateV2Response:
        """
        Creates a ServiceEligibility, returns immediately in the `PENDING` status.

        Parameters
        ----------
        service_type_id : str

        date_of_service : dt.datetime
            Full ISO8601 timestamp, including timezone

        state : ServiceEligibilityCreateV2RequestState
            2 letter US state code

        policy_ids : typing.Optional[typing.Sequence[ServiceEligibilityCreateV2RequestPolicyId]]
            Optional for cash-pay ServiceTypes; omit or pass [] when no policy is available

        clinical_info : typing.Optional[ServiceEligibilityCreateV2RequestClinicalInfo]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ServiceEligibilityCreateV2Response

        Examples
        --------
        import asyncio
        import datetime

        from rtaylor_205 import AsyncBridgeApiClient

        client = AsyncBridgeApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.service_eligibility.v_2.create_service_eligibility(
                service_type_id="serviceTypeId",
                date_of_service=datetime.datetime.fromisoformat(
                    "2024-01-15 09:30:00+00:00",
                ),
                state="AL",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_service_eligibility(
            service_type_id=service_type_id,
            date_of_service=date_of_service,
            state=state,
            policy_ids=policy_ids,
            clinical_info=clinical_info,
            request_options=request_options,
        )
        return _response.data
