# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .estimate_charge_authorize_stripe_v_1_response import EstimateChargeAuthorizeStripeV1Response
    from .estimate_charge_authorize_stripe_v_1_response_status import EstimateChargeAuthorizeStripeV1ResponseStatus
    from .estimate_charge_authorize_stripe_v_1_response_stripe import EstimateChargeAuthorizeStripeV1ResponseStripe
    from .estimate_charge_cancel_stripe_v_1_response import EstimateChargeCancelStripeV1Response
    from .estimate_charge_cancel_stripe_v_1_response_status import EstimateChargeCancelStripeV1ResponseStatus
    from .estimate_charge_cancel_stripe_v_1_response_stripe import EstimateChargeCancelStripeV1ResponseStripe
    from .estimate_charge_capture_stripe_v_1_response import EstimateChargeCaptureStripeV1Response
    from .estimate_charge_capture_stripe_v_1_response_status import EstimateChargeCaptureStripeV1ResponseStatus
    from .estimate_charge_capture_stripe_v_1_response_stripe import EstimateChargeCaptureStripeV1ResponseStripe
    from .estimate_charge_create_v_1_request import EstimateChargeCreateV1Request
    from .estimate_charge_create_v_1_response import EstimateChargeCreateV1Response
    from .estimate_charge_create_v_1_response_status import EstimateChargeCreateV1ResponseStatus
    from .estimate_charge_refund_stripe_v_1_response import EstimateChargeRefundStripeV1Response
    from .estimate_charge_refund_stripe_v_1_response_status import EstimateChargeRefundStripeV1ResponseStatus
    from .estimate_charge_refund_stripe_v_1_response_stripe import EstimateChargeRefundStripeV1ResponseStripe
_dynamic_imports: typing.Dict[str, str] = {
    "EstimateChargeAuthorizeStripeV1Response": ".estimate_charge_authorize_stripe_v_1_response",
    "EstimateChargeAuthorizeStripeV1ResponseStatus": ".estimate_charge_authorize_stripe_v_1_response_status",
    "EstimateChargeAuthorizeStripeV1ResponseStripe": ".estimate_charge_authorize_stripe_v_1_response_stripe",
    "EstimateChargeCancelStripeV1Response": ".estimate_charge_cancel_stripe_v_1_response",
    "EstimateChargeCancelStripeV1ResponseStatus": ".estimate_charge_cancel_stripe_v_1_response_status",
    "EstimateChargeCancelStripeV1ResponseStripe": ".estimate_charge_cancel_stripe_v_1_response_stripe",
    "EstimateChargeCaptureStripeV1Response": ".estimate_charge_capture_stripe_v_1_response",
    "EstimateChargeCaptureStripeV1ResponseStatus": ".estimate_charge_capture_stripe_v_1_response_status",
    "EstimateChargeCaptureStripeV1ResponseStripe": ".estimate_charge_capture_stripe_v_1_response_stripe",
    "EstimateChargeCreateV1Request": ".estimate_charge_create_v_1_request",
    "EstimateChargeCreateV1Response": ".estimate_charge_create_v_1_response",
    "EstimateChargeCreateV1ResponseStatus": ".estimate_charge_create_v_1_response_status",
    "EstimateChargeRefundStripeV1Response": ".estimate_charge_refund_stripe_v_1_response",
    "EstimateChargeRefundStripeV1ResponseStatus": ".estimate_charge_refund_stripe_v_1_response_status",
    "EstimateChargeRefundStripeV1ResponseStripe": ".estimate_charge_refund_stripe_v_1_response_stripe",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "EstimateChargeAuthorizeStripeV1Response",
    "EstimateChargeAuthorizeStripeV1ResponseStatus",
    "EstimateChargeAuthorizeStripeV1ResponseStripe",
    "EstimateChargeCancelStripeV1Response",
    "EstimateChargeCancelStripeV1ResponseStatus",
    "EstimateChargeCancelStripeV1ResponseStripe",
    "EstimateChargeCaptureStripeV1Response",
    "EstimateChargeCaptureStripeV1ResponseStatus",
    "EstimateChargeCaptureStripeV1ResponseStripe",
    "EstimateChargeCreateV1Request",
    "EstimateChargeCreateV1Response",
    "EstimateChargeCreateV1ResponseStatus",
    "EstimateChargeRefundStripeV1Response",
    "EstimateChargeRefundStripeV1ResponseStatus",
    "EstimateChargeRefundStripeV1ResponseStripe",
]
