# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .payer_group_get_v_1_response_health import PayerGroupGetV1ResponseHealth


class PayerGroupGetV1Response(UniversalBaseModel):
    id: str
    slug: str
    name: str
    primary: bool
    health: typing.Optional[PayerGroupGetV1ResponseHealth] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
