# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawConsentVersionsClient, RawConsentVersionsClient
from .types.consent_versions_list_v_1_response import ConsentVersionsListV1Response


class ConsentVersionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawConsentVersionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawConsentVersionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawConsentVersionsClient
        """
        return self._raw_client

    def list_consent_versions(
        self,
        *,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ConsentVersionsListV1Response:
        """
        Parameters
        ----------
        page : typing.Optional[int]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConsentVersionsListV1Response

        Examples
        --------
        from usebridge_api import BridgeApiClient

        client = BridgeApiClient(
            api_key="YOUR_API_KEY",
        )
        client.consent_versions.list_consent_versions()
        """
        _response = self._raw_client.list_consent_versions(page=page, limit=limit, request_options=request_options)
        return _response.data


class AsyncConsentVersionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawConsentVersionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawConsentVersionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawConsentVersionsClient
        """
        return self._raw_client

    async def list_consent_versions(
        self,
        *,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ConsentVersionsListV1Response:
        """
        Parameters
        ----------
        page : typing.Optional[int]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConsentVersionsListV1Response

        Examples
        --------
        import asyncio

        from usebridge_api import AsyncBridgeApiClient

        client = AsyncBridgeApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.consent_versions.list_consent_versions()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_consent_versions(
            page=page, limit=limit, request_options=request_options
        )
        return _response.data
