# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .policy_create_v_2_request import PolicyCreateV2Request
    from .policy_create_v_2_request_person import PolicyCreateV2RequestPerson
    from .policy_create_v_2_request_state import PolicyCreateV2RequestState
    from .policy_create_v_2_response import PolicyCreateV2Response
    from .policy_create_v_2_response_error import PolicyCreateV2ResponseError
    from .policy_create_v_2_response_latest import PolicyCreateV2ResponseLatest
    from .policy_create_v_2_response_payer import PolicyCreateV2ResponsePayer
    from .policy_create_v_2_response_person import PolicyCreateV2ResponsePerson
    from .policy_create_v_2_response_policy_holder import PolicyCreateV2ResponsePolicyHolder
    from .policy_create_v_2_response_relationship import PolicyCreateV2ResponseRelationship
    from .policy_create_v_2_response_state import PolicyCreateV2ResponseState
    from .policy_create_v_2_response_status import PolicyCreateV2ResponseStatus
_dynamic_imports: typing.Dict[str, str] = {
    "PolicyCreateV2Request": ".policy_create_v_2_request",
    "PolicyCreateV2RequestPerson": ".policy_create_v_2_request_person",
    "PolicyCreateV2RequestState": ".policy_create_v_2_request_state",
    "PolicyCreateV2Response": ".policy_create_v_2_response",
    "PolicyCreateV2ResponseError": ".policy_create_v_2_response_error",
    "PolicyCreateV2ResponseLatest": ".policy_create_v_2_response_latest",
    "PolicyCreateV2ResponsePayer": ".policy_create_v_2_response_payer",
    "PolicyCreateV2ResponsePerson": ".policy_create_v_2_response_person",
    "PolicyCreateV2ResponsePolicyHolder": ".policy_create_v_2_response_policy_holder",
    "PolicyCreateV2ResponseRelationship": ".policy_create_v_2_response_relationship",
    "PolicyCreateV2ResponseState": ".policy_create_v_2_response_state",
    "PolicyCreateV2ResponseStatus": ".policy_create_v_2_response_status",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "PolicyCreateV2Request",
    "PolicyCreateV2RequestPerson",
    "PolicyCreateV2RequestState",
    "PolicyCreateV2Response",
    "PolicyCreateV2ResponseError",
    "PolicyCreateV2ResponseLatest",
    "PolicyCreateV2ResponsePayer",
    "PolicyCreateV2ResponsePerson",
    "PolicyCreateV2ResponsePolicyHolder",
    "PolicyCreateV2ResponseRelationship",
    "PolicyCreateV2ResponseState",
    "PolicyCreateV2ResponseStatus",
]
