# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .event_get_v_1_response import EventGetV1Response
    from .event_get_v_1_response_event_type import EventGetV1ResponseEventType
    from .events_list_v_1_order_created_at import EventsListV1OrderCreatedAt
    from .events_list_v_1_response import EventsListV1Response
    from .events_list_v_1_response_item import EventsListV1ResponseItem
    from .events_list_v_1_response_item_event_type import EventsListV1ResponseItemEventType
_dynamic_imports: typing.Dict[str, str] = {
    "EventGetV1Response": ".event_get_v_1_response",
    "EventGetV1ResponseEventType": ".event_get_v_1_response_event_type",
    "EventsListV1OrderCreatedAt": ".events_list_v_1_order_created_at",
    "EventsListV1Response": ".events_list_v_1_response",
    "EventsListV1ResponseItem": ".events_list_v_1_response_item",
    "EventsListV1ResponseItemEventType": ".events_list_v_1_response_item_event_type",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "EventGetV1Response",
    "EventGetV1ResponseEventType",
    "EventsListV1OrderCreatedAt",
    "EventsListV1Response",
    "EventsListV1ResponseItem",
    "EventsListV1ResponseItemEventType",
]
