# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .event_get_v_1_response_event_type import EventGetV1ResponseEventType


class EventGetV1Response(UniversalBaseModel):
    api_version: typing_extensions.Annotated[str, FieldMetadata(alias="apiVersion"), pydantic.Field(alias="apiVersion")]
    event_id: typing_extensions.Annotated[str, FieldMetadata(alias="eventId"), pydantic.Field(alias="eventId")]
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]
    event_type: typing_extensions.Annotated[
        EventGetV1ResponseEventType, FieldMetadata(alias="eventType"), pydantic.Field(alias="eventType")
    ]
    object_type: typing_extensions.Annotated[str, FieldMetadata(alias="objectType"), pydantic.Field(alias="objectType")]
    object_id: typing_extensions.Annotated[str, FieldMetadata(alias="objectId"), pydantic.Field(alias="objectId")]
    data: typing.Optional[typing.Any] = None
    previous: typing.Optional[typing.Any] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
