# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .note_addenda_list_v_1_response_item_data_field_monitoring_data_element_value import (
    NoteAddendaListV1ResponseItemDataFieldMonitoringDataElementValue,
)


class NoteAddendaListV1ResponseItemDataFieldMonitoringDatum(UniversalBaseModel):
    date: str
    values: typing.List[NoteAddendaListV1ResponseItemDataFieldMonitoringDataElementValue]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
