# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .note_create_v_1_response_data_field_monitoring_data_element_value import (
    NoteCreateV1ResponseDataFieldMonitoringDataElementValue,
)


class NoteCreateV1ResponseDataFieldMonitoringDatum(UniversalBaseModel):
    date: str
    values: typing.List[NoteCreateV1ResponseDataFieldMonitoringDataElementValue]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
