# This file was auto-generated by Fern from our API Definition.

import typing

NoteAddendumCreateV1RequestDataFieldScoredAssessmentsElementType = typing.Union[
    typing.Literal["PHQ-9", "GAD-7", "SDOH-PRAPARE", "SDOH-AHC-HRSN", "SDOH-VI-SPDAT", "SDOH-CORE-5-SDH"], typing.Any
]
