# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
from json.decoder import JSONDecodeError

from ...core.api_error import ApiError
from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.http_response import AsyncHttpResponse, HttpResponse
from ...core.parse_error import ParsingError
from ...core.pydantic_utilities import parse_obj_as
from ...core.request_options import RequestOptions
from ...core.serialization import convert_and_respect_annotation_metadata
from .types.policy_create_v_2_request_person import PolicyCreateV2RequestPerson
from .types.policy_create_v_2_request_state import PolicyCreateV2RequestState
from .types.policy_create_v_2_response import PolicyCreateV2Response
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawV2Client:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def create_policy(
        self,
        *,
        person: PolicyCreateV2RequestPerson,
        state: PolicyCreateV2RequestState,
        payer_id: str,
        external_id: typing.Optional[str] = OMIT,
        member_id: typing.Optional[str] = OMIT,
        date_of_service: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PolicyCreateV2Response]:
        """
        Creates a Policy, returning immediately with status of `PENDING`. Use the Get Policy API, or monitor webhooks, to receive updates.

        Parameters
        ----------
        person : PolicyCreateV2RequestPerson

        state : PolicyCreateV2RequestState
            2 letter US state code

        payer_id : str

        external_id : typing.Optional[str]
            Optional unique identifier

        member_id : typing.Optional[str]

        date_of_service : typing.Optional[dt.datetime]
            Full ISO8601 timestamp, including timezone

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PolicyCreateV2Response]
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/policies/v2",
            method="POST",
            json={
                "externalId": external_id,
                "person": convert_and_respect_annotation_metadata(
                    object_=person, annotation=PolicyCreateV2RequestPerson, direction="write"
                ),
                "state": state,
                "payerId": payer_id,
                "memberId": member_id,
                "dateOfService": date_of_service,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PolicyCreateV2Response,
                    parse_obj_as(
                        type_=PolicyCreateV2Response,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawV2Client:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def create_policy(
        self,
        *,
        person: PolicyCreateV2RequestPerson,
        state: PolicyCreateV2RequestState,
        payer_id: str,
        external_id: typing.Optional[str] = OMIT,
        member_id: typing.Optional[str] = OMIT,
        date_of_service: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PolicyCreateV2Response]:
        """
        Creates a Policy, returning immediately with status of `PENDING`. Use the Get Policy API, or monitor webhooks, to receive updates.

        Parameters
        ----------
        person : PolicyCreateV2RequestPerson

        state : PolicyCreateV2RequestState
            2 letter US state code

        payer_id : str

        external_id : typing.Optional[str]
            Optional unique identifier

        member_id : typing.Optional[str]

        date_of_service : typing.Optional[dt.datetime]
            Full ISO8601 timestamp, including timezone

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PolicyCreateV2Response]
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/policies/v2",
            method="POST",
            json={
                "externalId": external_id,
                "person": convert_and_respect_annotation_metadata(
                    object_=person, annotation=PolicyCreateV2RequestPerson, direction="write"
                ),
                "state": state,
                "payerId": payer_id,
                "memberId": member_id,
                "dateOfService": date_of_service,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PolicyCreateV2Response,
                    parse_obj_as(
                        type_=PolicyCreateV2Response,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
