# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawProvidersClient, RawProvidersClient
from .types.provider_get_v_1_response import ProviderGetV1Response
from .types.provider_post_v_1_request_provider import ProviderPostV1RequestProvider
from .types.provider_post_v_1_response import ProviderPostV1Response
from .types.provider_update_v_1_response import ProviderUpdateV1Response
from .types.providers_list_v_1_response import ProvidersListV1Response

if typing.TYPE_CHECKING:
    from .enrollment.client import AsyncEnrollmentClient, EnrollmentClient
# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ProvidersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawProvidersClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._enrollment: typing.Optional[EnrollmentClient] = None

    @property
    def with_raw_response(self) -> RawProvidersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawProvidersClient
        """
        return self._raw_client

    def submit_providers(
        self,
        *,
        providers: typing.Sequence[ProviderPostV1RequestProvider],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ProviderPostV1Response:
        """
        **Production only:** This endpoint is only available in Production and will not work in Sandbox.

        Parameters
        ----------
        providers : typing.Sequence[ProviderPostV1RequestProvider]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProviderPostV1Response

        Examples
        --------
        from rtaylor_205 import BridgeApiClient
        from rtaylor_205.providers import ProviderPostV1RequestProvider

        client = BridgeApiClient(
            api_key="YOUR_API_KEY",
        )
        client.providers.submit_providers(
            providers=[
                ProviderPostV1RequestProvider(
                    npi="npi",
                    email="email",
                    caqh_id="caqhId",
                    caqh_username="caqhUsername",
                    caqh_password="caqhPassword",
                ),
                ProviderPostV1RequestProvider(
                    npi="npi",
                    email="email",
                    caqh_id="caqhId",
                    caqh_username="caqhUsername",
                    caqh_password="caqhPassword",
                ),
            ],
        )
        """
        _response = self._raw_client.submit_providers(providers=providers, request_options=request_options)
        return _response.data

    def list_providers(
        self,
        *,
        filter_active: typing.Optional[bool] = None,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ProvidersListV1Response:
        """
        Parameters
        ----------
        filter_active : typing.Optional[bool]
            Value is a raw boolean, example filter.active=true

        page : typing.Optional[int]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProvidersListV1Response

        Examples
        --------
        from rtaylor_205 import BridgeApiClient

        client = BridgeApiClient(
            api_key="YOUR_API_KEY",
        )
        client.providers.list_providers()
        """
        _response = self._raw_client.list_providers(
            filter_active=filter_active, page=page, limit=limit, request_options=request_options
        )
        return _response.data

    def get_provider(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ProviderGetV1Response:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProviderGetV1Response

        Examples
        --------
        from rtaylor_205 import BridgeApiClient

        client = BridgeApiClient(
            api_key="YOUR_API_KEY",
        )
        client.providers.get_provider(
            id="id",
        )
        """
        _response = self._raw_client.get_provider(id, request_options=request_options)
        return _response.data

    def update_provider(
        self,
        id: str,
        *,
        external_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ProviderUpdateV1Response:
        """
        Parameters
        ----------
        id : str

        external_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProviderUpdateV1Response

        Examples
        --------
        from rtaylor_205 import BridgeApiClient

        client = BridgeApiClient(
            api_key="YOUR_API_KEY",
        )
        client.providers.update_provider(
            id="id",
        )
        """
        _response = self._raw_client.update_provider(id, external_id=external_id, request_options=request_options)
        return _response.data

    @property
    def enrollment(self):
        if self._enrollment is None:
            from .enrollment.client import EnrollmentClient  # noqa: E402

            self._enrollment = EnrollmentClient(client_wrapper=self._client_wrapper)
        return self._enrollment


class AsyncProvidersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawProvidersClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._enrollment: typing.Optional[AsyncEnrollmentClient] = None

    @property
    def with_raw_response(self) -> AsyncRawProvidersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawProvidersClient
        """
        return self._raw_client

    async def submit_providers(
        self,
        *,
        providers: typing.Sequence[ProviderPostV1RequestProvider],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ProviderPostV1Response:
        """
        **Production only:** This endpoint is only available in Production and will not work in Sandbox.

        Parameters
        ----------
        providers : typing.Sequence[ProviderPostV1RequestProvider]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProviderPostV1Response

        Examples
        --------
        import asyncio

        from rtaylor_205 import AsyncBridgeApiClient
        from rtaylor_205.providers import ProviderPostV1RequestProvider

        client = AsyncBridgeApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.providers.submit_providers(
                providers=[
                    ProviderPostV1RequestProvider(
                        npi="npi",
                        email="email",
                        caqh_id="caqhId",
                        caqh_username="caqhUsername",
                        caqh_password="caqhPassword",
                    ),
                    ProviderPostV1RequestProvider(
                        npi="npi",
                        email="email",
                        caqh_id="caqhId",
                        caqh_username="caqhUsername",
                        caqh_password="caqhPassword",
                    ),
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.submit_providers(providers=providers, request_options=request_options)
        return _response.data

    async def list_providers(
        self,
        *,
        filter_active: typing.Optional[bool] = None,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ProvidersListV1Response:
        """
        Parameters
        ----------
        filter_active : typing.Optional[bool]
            Value is a raw boolean, example filter.active=true

        page : typing.Optional[int]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProvidersListV1Response

        Examples
        --------
        import asyncio

        from rtaylor_205 import AsyncBridgeApiClient

        client = AsyncBridgeApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.providers.list_providers()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_providers(
            filter_active=filter_active, page=page, limit=limit, request_options=request_options
        )
        return _response.data

    async def get_provider(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ProviderGetV1Response:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProviderGetV1Response

        Examples
        --------
        import asyncio

        from rtaylor_205 import AsyncBridgeApiClient

        client = AsyncBridgeApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.providers.get_provider(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_provider(id, request_options=request_options)
        return _response.data

    async def update_provider(
        self,
        id: str,
        *,
        external_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ProviderUpdateV1Response:
        """
        Parameters
        ----------
        id : str

        external_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProviderUpdateV1Response

        Examples
        --------
        import asyncio

        from rtaylor_205 import AsyncBridgeApiClient

        client = AsyncBridgeApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.providers.update_provider(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_provider(id, external_id=external_id, request_options=request_options)
        return _response.data

    @property
    def enrollment(self):
        if self._enrollment is None:
            from .enrollment.client import AsyncEnrollmentClient  # noqa: E402

            self._enrollment = AsyncEnrollmentClient(client_wrapper=self._client_wrapper)
        return self._enrollment
