# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        FeeCaptureStripeV1Response,
        FeeCaptureStripeV1ResponseStatus,
        FeeCaptureStripeV1ResponseStripe,
        FeeCaptureStripeV1ResponseType,
        FeeCreateV1Request,
        FeeCreateV1RequestType,
        FeeCreateV1Response,
        FeeCreateV1ResponseStatus,
        FeeCreateV1ResponseType,
        FeeRefundStripeV1Response,
        FeeRefundStripeV1ResponseStatus,
        FeeRefundStripeV1ResponseStripe,
        FeeRefundStripeV1ResponseType,
        FeesListV1FilterStatus,
        FeesListV1Response,
        FeesListV1ResponseItem,
        FeesListV1ResponseItemStatus,
        FeesListV1ResponseItemType,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "FeeCaptureStripeV1Response": ".types",
    "FeeCaptureStripeV1ResponseStatus": ".types",
    "FeeCaptureStripeV1ResponseStripe": ".types",
    "FeeCaptureStripeV1ResponseType": ".types",
    "FeeCreateV1Request": ".types",
    "FeeCreateV1RequestType": ".types",
    "FeeCreateV1Response": ".types",
    "FeeCreateV1ResponseStatus": ".types",
    "FeeCreateV1ResponseType": ".types",
    "FeeRefundStripeV1Response": ".types",
    "FeeRefundStripeV1ResponseStatus": ".types",
    "FeeRefundStripeV1ResponseStripe": ".types",
    "FeeRefundStripeV1ResponseType": ".types",
    "FeesListV1FilterStatus": ".types",
    "FeesListV1Response": ".types",
    "FeesListV1ResponseItem": ".types",
    "FeesListV1ResponseItemStatus": ".types",
    "FeesListV1ResponseItemType": ".types",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "FeeCaptureStripeV1Response",
    "FeeCaptureStripeV1ResponseStatus",
    "FeeCaptureStripeV1ResponseStripe",
    "FeeCaptureStripeV1ResponseType",
    "FeeCreateV1Request",
    "FeeCreateV1RequestType",
    "FeeCreateV1Response",
    "FeeCreateV1ResponseStatus",
    "FeeCreateV1ResponseType",
    "FeeRefundStripeV1Response",
    "FeeRefundStripeV1ResponseStatus",
    "FeeRefundStripeV1ResponseStripe",
    "FeeRefundStripeV1ResponseType",
    "FeesListV1FilterStatus",
    "FeesListV1Response",
    "FeesListV1ResponseItem",
    "FeesListV1ResponseItemStatus",
    "FeesListV1ResponseItemType",
]
