# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .provider_enrollment_status_get_v_1_response_payer_groups_value_states_value_license_status import (
    ProviderEnrollmentStatusGetV1ResponsePayerGroupsValueStatesValueLicenseStatus,
)
from .provider_enrollment_status_get_v_1_response_payer_groups_value_states_value_lines_of_business import (
    ProviderEnrollmentStatusGetV1ResponsePayerGroupsValueStatesValueLinesOfBusiness,
)


class ProviderEnrollmentStatusGetV1ResponsePayerGroupsValueStates(UniversalBaseModel):
    license_status: typing_extensions.Annotated[
        ProviderEnrollmentStatusGetV1ResponsePayerGroupsValueStatesValueLicenseStatus,
        FieldMetadata(alias="licenseStatus"),
        pydantic.Field(alias="licenseStatus"),
    ]
    lines_of_business: typing_extensions.Annotated[
        ProviderEnrollmentStatusGetV1ResponsePayerGroupsValueStatesValueLinesOfBusiness,
        FieldMetadata(alias="linesOfBusiness"),
        pydantic.Field(
            alias="linesOfBusiness",
            description="Enrollment status within the payer group and state, by applicable line of business",
        ),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
