# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .provider_post_v_1_response_failed_element_provider_type import ProviderPostV1ResponseFailedElementProviderType


class ProviderPostV1ResponseFailed(UniversalBaseModel):
    caqh_id: typing_extensions.Annotated[str, FieldMetadata(alias="caqhId"), pydantic.Field(alias="caqhId")]
    credential: typing.Optional[str] = None
    email: str
    error: typing.Optional[str] = None
    external_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="externalId"), pydantic.Field(alias="externalId")
    ] = None
    first_name: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="firstName"), pydantic.Field(alias="firstName")
    ] = None
    last_name: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="lastName"), pydantic.Field(alias="lastName")
    ] = None
    npi: str
    provider_type: typing_extensions.Annotated[
        typing.Optional[ProviderPostV1ResponseFailedElementProviderType],
        FieldMetadata(alias="providerType"),
        pydantic.Field(alias="providerType"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
