# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class ProviderPostV1RequestProvider(UniversalBaseModel):
    npi: str
    email: str
    caqh_id: typing_extensions.Annotated[str, FieldMetadata(alias="caqhId"), pydantic.Field(alias="caqhId")]
    caqh_username: typing_extensions.Annotated[
        str, FieldMetadata(alias="caqhUsername"), pydantic.Field(alias="caqhUsername")
    ]
    caqh_password: typing_extensions.Annotated[
        str, FieldMetadata(alias="caqhPassword"), pydantic.Field(alias="caqhPassword")
    ]
    external_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="externalId"), pydantic.Field(alias="externalId")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
