# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from .raw_client import AsyncRawSetupIntentClient, RawSetupIntentClient
from .types.setup_intent_create_stripe_v_1_response import SetupIntentCreateStripeV1Response

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SetupIntentClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSetupIntentClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSetupIntentClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSetupIntentClient
        """
        return self._raw_client

    def create_stripe_setup_intent(
        self, *, patient_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> SetupIntentCreateStripeV1Response:
        """
        This endpoint can only be used after setting up the billing integration. Refer to the [billing integration documentation](/documentation/integrations/billing/overview) for more details.

        Parameters
        ----------
        patient_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SetupIntentCreateStripeV1Response

        Examples
        --------
        from rtaylor_205 import BridgeApiClient

        client = BridgeApiClient(
            api_key="YOUR_API_KEY",
        )
        client.billing.setup_intent.create_stripe_setup_intent(
            patient_id="patientId",
        )
        """
        _response = self._raw_client.create_stripe_setup_intent(patient_id=patient_id, request_options=request_options)
        return _response.data


class AsyncSetupIntentClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSetupIntentClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSetupIntentClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSetupIntentClient
        """
        return self._raw_client

    async def create_stripe_setup_intent(
        self, *, patient_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> SetupIntentCreateStripeV1Response:
        """
        This endpoint can only be used after setting up the billing integration. Refer to the [billing integration documentation](/documentation/integrations/billing/overview) for more details.

        Parameters
        ----------
        patient_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SetupIntentCreateStripeV1Response

        Examples
        --------
        import asyncio

        from rtaylor_205 import AsyncBridgeApiClient

        client = AsyncBridgeApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.billing.setup_intent.create_stripe_setup_intent(
                patient_id="patientId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_stripe_setup_intent(
            patient_id=patient_id, request_options=request_options
        )
        return _response.data
