# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from .raw_client import AsyncRawV2Client, RawV2Client
from .types.patient_create_v_2_request_address import PatientCreateV2RequestAddress
from .types.patient_create_v_2_request_coverage import PatientCreateV2RequestCoverage
from .types.patient_create_v_2_request_metadata import PatientCreateV2RequestMetadata
from .types.patient_create_v_2_response import PatientCreateV2Response
from .types.patient_get_v_2_response import PatientGetV2Response

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class V2Client:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawV2Client(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawV2Client:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawV2Client
        """
        return self._raw_client

    def create_patient(
        self,
        *,
        first_name: str,
        last_name: str,
        email: str,
        date_of_birth: dt.datetime,
        external_id: typing.Optional[str] = OMIT,
        phone: typing.Optional[str] = OMIT,
        address: typing.Optional[PatientCreateV2RequestAddress] = OMIT,
        coverage: typing.Optional[typing.Sequence[PatientCreateV2RequestCoverage]] = OMIT,
        metadata: typing.Optional[PatientCreateV2RequestMetadata] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PatientCreateV2Response:
        """
        Parameters
        ----------
        first_name : str

        last_name : str

        email : str

        date_of_birth : dt.datetime

        external_id : typing.Optional[str]

        phone : typing.Optional[str]

        address : typing.Optional[PatientCreateV2RequestAddress]

        coverage : typing.Optional[typing.Sequence[PatientCreateV2RequestCoverage]]
            Sets the active Policies to use for this Patient, applied to un-billed Services. In all cases, maximum of 1 element, secondary insurance does not need to be collected. For uninsured/cash-pay patients, set to an empty array.

        metadata : typing.Optional[PatientCreateV2RequestMetadata]
            Customizable object of string to string key-value data

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PatientCreateV2Response

        Examples
        --------
        import datetime

        from usebridge_api import BridgeApiClient

        client = BridgeApiClient(
            api_key="YOUR_API_KEY",
        )
        client.patients.v_2.create_patient(
            first_name="firstName",
            last_name="lastName",
            email="email",
            date_of_birth=datetime.datetime.fromisoformat(
                "2024-01-15 09:30:00+00:00",
            ),
        )
        """
        _response = self._raw_client.create_patient(
            first_name=first_name,
            last_name=last_name,
            email=email,
            date_of_birth=date_of_birth,
            external_id=external_id,
            phone=phone,
            address=address,
            coverage=coverage,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    def get_patient(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> PatientGetV2Response:
        """
        Resolves a Patient by either `id` or `externalId`

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PatientGetV2Response

        Examples
        --------
        from usebridge_api import BridgeApiClient

        client = BridgeApiClient(
            api_key="YOUR_API_KEY",
        )
        client.patients.v_2.get_patient(
            id="id",
        )
        """
        _response = self._raw_client.get_patient(id, request_options=request_options)
        return _response.data


class AsyncV2Client:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawV2Client(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawV2Client:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawV2Client
        """
        return self._raw_client

    async def create_patient(
        self,
        *,
        first_name: str,
        last_name: str,
        email: str,
        date_of_birth: dt.datetime,
        external_id: typing.Optional[str] = OMIT,
        phone: typing.Optional[str] = OMIT,
        address: typing.Optional[PatientCreateV2RequestAddress] = OMIT,
        coverage: typing.Optional[typing.Sequence[PatientCreateV2RequestCoverage]] = OMIT,
        metadata: typing.Optional[PatientCreateV2RequestMetadata] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PatientCreateV2Response:
        """
        Parameters
        ----------
        first_name : str

        last_name : str

        email : str

        date_of_birth : dt.datetime

        external_id : typing.Optional[str]

        phone : typing.Optional[str]

        address : typing.Optional[PatientCreateV2RequestAddress]

        coverage : typing.Optional[typing.Sequence[PatientCreateV2RequestCoverage]]
            Sets the active Policies to use for this Patient, applied to un-billed Services. In all cases, maximum of 1 element, secondary insurance does not need to be collected. For uninsured/cash-pay patients, set to an empty array.

        metadata : typing.Optional[PatientCreateV2RequestMetadata]
            Customizable object of string to string key-value data

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PatientCreateV2Response

        Examples
        --------
        import asyncio
        import datetime

        from usebridge_api import AsyncBridgeApiClient

        client = AsyncBridgeApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.patients.v_2.create_patient(
                first_name="firstName",
                last_name="lastName",
                email="email",
                date_of_birth=datetime.datetime.fromisoformat(
                    "2024-01-15 09:30:00+00:00",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_patient(
            first_name=first_name,
            last_name=last_name,
            email=email,
            date_of_birth=date_of_birth,
            external_id=external_id,
            phone=phone,
            address=address,
            coverage=coverage,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    async def get_patient(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PatientGetV2Response:
        """
        Resolves a Patient by either `id` or `externalId`

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PatientGetV2Response

        Examples
        --------
        import asyncio

        from usebridge_api import AsyncBridgeApiClient

        client = AsyncBridgeApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.patients.v_2.get_patient(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_patient(id, request_options=request_options)
        return _response.data
