# This file was auto-generated by Fern from our API Definition.

from .service_create_v_1_response_service_type_field_provider_types_element import (
    ServiceCreateV1ResponseServiceTypeFieldProviderTypesElement,
)

ServiceCreateV1ResponseServiceTypeFieldProviderType = ServiceCreateV1ResponseServiceTypeFieldProviderTypesElement
