# This file was auto-generated by Fern from our API Definition.

import typing

ServicesListV1ResponseItemServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldMetric = (
    typing.Union[typing.Literal["VISIT", "UNITS"], typing.Any]
)
