# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .service_set_ready_v_1_response_cancellation_reason import ServiceSetReadyV1ResponseCancellationReason
from .service_set_ready_v_1_response_claim_status import ServiceSetReadyV1ResponseClaimStatus
from .service_set_ready_v_1_response_coverage_status import ServiceSetReadyV1ResponseCoverageStatus
from .service_set_ready_v_1_response_location import ServiceSetReadyV1ResponseLocation
from .service_set_ready_v_1_response_metadata import ServiceSetReadyV1ResponseMetadata
from .service_set_ready_v_1_response_patient_responsibility import ServiceSetReadyV1ResponsePatientResponsibility
from .service_set_ready_v_1_response_payment import ServiceSetReadyV1ResponsePayment
from .service_set_ready_v_1_response_provider import ServiceSetReadyV1ResponseProvider
from .service_set_ready_v_1_response_responsible_party import ServiceSetReadyV1ResponseResponsibleParty
from .service_set_ready_v_1_response_service_eligibility import ServiceSetReadyV1ResponseServiceEligibility
from .service_set_ready_v_1_response_service_type import ServiceSetReadyV1ResponseServiceType
from .service_set_ready_v_1_response_status import ServiceSetReadyV1ResponseStatus
from .service_set_ready_v_1_response_task import ServiceSetReadyV1ResponseTask


class ServiceSetReadyV1Response(UniversalBaseModel):
    id: str
    organization_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="organizationId"), pydantic.Field(alias="organizationId")
    ]
    status: ServiceSetReadyV1ResponseStatus
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]
    service_type: typing_extensions.Annotated[
        ServiceSetReadyV1ResponseServiceType, FieldMetadata(alias="serviceType"), pydantic.Field(alias="serviceType")
    ]
    date_of_service: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="dateOfService"), pydantic.Field(alias="dateOfService")
    ]
    external_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="externalId"), pydantic.Field(alias="externalId")
    ] = None
    patient_id: typing_extensions.Annotated[str, FieldMetadata(alias="patientId"), pydantic.Field(alias="patientId")]
    location: ServiceSetReadyV1ResponseLocation = pydantic.Field()
    """
    Location of the Patient at the date of service, requires only the `state` value for telehealth
    """

    note_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="noteId"), pydantic.Field(alias="noteId")
    ] = None
    service_eligibility: typing_extensions.Annotated[
        ServiceSetReadyV1ResponseServiceEligibility,
        FieldMetadata(alias="serviceEligibility"),
        pydantic.Field(alias="serviceEligibility"),
    ]
    coverage_status: typing_extensions.Annotated[
        ServiceSetReadyV1ResponseCoverageStatus,
        FieldMetadata(alias="coverageStatus"),
        pydantic.Field(alias="coverageStatus"),
    ]
    provider: ServiceSetReadyV1ResponseProvider
    payments: typing.List[ServiceSetReadyV1ResponsePayment]
    responsible_party: typing_extensions.Annotated[
        ServiceSetReadyV1ResponseResponsibleParty,
        FieldMetadata(alias="responsibleParty"),
        pydantic.Field(alias="responsibleParty"),
    ]
    patient_responsibility: typing_extensions.Annotated[
        ServiceSetReadyV1ResponsePatientResponsibility,
        FieldMetadata(alias="patientResponsibility"),
        pydantic.Field(alias="patientResponsibility"),
    ]
    tasks: typing.List[ServiceSetReadyV1ResponseTask]
    claim_status: typing_extensions.Annotated[
        typing.Optional[ServiceSetReadyV1ResponseClaimStatus],
        FieldMetadata(alias="claimStatus"),
        pydantic.Field(alias="claimStatus"),
    ] = None
    prior_authorization_number: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="priorAuthorizationNumber"),
        pydantic.Field(alias="priorAuthorizationNumber"),
    ] = None
    cancellation_reason: typing_extensions.Annotated[
        typing.Optional[ServiceSetReadyV1ResponseCancellationReason],
        FieldMetadata(alias="cancellationReason"),
        pydantic.Field(alias="cancellationReason"),
    ] = None
    metadata: typing.Optional[ServiceSetReadyV1ResponseMetadata] = pydantic.Field(default=None)
    """
    Customizable object of string to string key-value data
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
