# This file was auto-generated by Fern from our API Definition.

import typing

ServiceGetV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod = typing.Union[
    typing.Literal["ANNUAL", "BENEFIT_YEAR", "LIFETIME"], typing.Any
]
