# This file was auto-generated by Fern from our API Definition.

from .service_stream_v_1_response_service_type_field_provider_types_element import (
    ServiceStreamV1ResponseServiceTypeFieldProviderTypesElement,
)

ServiceStreamV1ResponseServiceTypeFieldProviderType = ServiceStreamV1ResponseServiceTypeFieldProviderTypesElement
