# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .services_list_v_1_response_item_service_eligibility_field_conditional_patient_responsibilities_element_limit_field_metric import (
    ServicesListV1ResponseItemServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldMetric,
)
from .services_list_v_1_response_item_service_eligibility_field_conditional_patient_responsibilities_element_limit_field_period import (
    ServicesListV1ResponseItemServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod,
)
from .services_list_v_1_response_item_service_eligibility_field_conditional_patient_responsibilities_element_limit_field_type import (
    ServicesListV1ResponseItemServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType,
)
from .services_list_v_1_response_item_service_eligibility_field_conditional_patient_responsibilities_element_limit_field_units import (
    ServicesListV1ResponseItemServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldUnits,
)


class ServicesListV1ResponseItemServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimit(
    UniversalBaseModel
):
    type: ServicesListV1ResponseItemServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType
    value: typing.Optional[int] = None
    metric: typing.Optional[
        ServicesListV1ResponseItemServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldMetric
    ] = None
    period: typing.Optional[
        ServicesListV1ResponseItemServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod
    ] = None
    units: typing.Optional[
        ServicesListV1ResponseItemServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldUnits
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
