# This file was auto-generated by Fern from our API Definition.

import typing

ServiceGetV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementPatientResponsibilityFieldDeductibleType = typing.Union[
    typing.Literal["INDIVIDUAL", "FAMILY"], typing.Any
]
