# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .service_set_ready_v_1_response_service_eligibility_field_conditional_patient_responsibilities_element_limit_field_metric import (
    ServiceSetReadyV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldMetric,
)
from .service_set_ready_v_1_response_service_eligibility_field_conditional_patient_responsibilities_element_limit_field_period import (
    ServiceSetReadyV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod,
)
from .service_set_ready_v_1_response_service_eligibility_field_conditional_patient_responsibilities_element_limit_field_type import (
    ServiceSetReadyV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType,
)
from .service_set_ready_v_1_response_service_eligibility_field_conditional_patient_responsibilities_element_limit_field_units import (
    ServiceSetReadyV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldUnits,
)


class ServiceSetReadyV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimit(
    UniversalBaseModel
):
    type: ServiceSetReadyV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType
    value: typing.Optional[int] = None
    metric: typing.Optional[
        ServiceSetReadyV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldMetric
    ] = None
    period: typing.Optional[
        ServiceSetReadyV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod
    ] = None
    units: typing.Optional[
        ServiceSetReadyV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldUnits
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
