# This file was auto-generated by Fern from our API Definition.

import typing

ServiceStreamV1ResponseServiceEligibilityFieldPatientResponsibilityFieldDeductibleType = typing.Union[
    typing.Literal["INDIVIDUAL", "FAMILY"], typing.Any
]
