# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .services_list_v_1_response_item_tasks_element_type import ServicesListV1ResponseItemTasksElementType


class ServicesListV1ResponseItemTask(UniversalBaseModel):
    type: ServicesListV1ResponseItemTasksElementType
    memo: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
