# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from .types.patient_consent_create_v_1_request_type import PatientConsentCreateV1RequestType
from .types.patient_consent_create_v_1_response import PatientConsentCreateV1Response
from .types.patient_consents_list_v_1_response import PatientConsentsListV1Response
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawConsentClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_patient_consents(
        self,
        id: str,
        *,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PatientConsentsListV1Response]:
        """
        Parameters
        ----------
        id : str

        page : typing.Optional[int]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PatientConsentsListV1Response]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/patients/{encode_path_param(id)}/consent",
            method="GET",
            params={
                "page": page,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PatientConsentsListV1Response,
                    parse_obj_as(
                        type_=PatientConsentsListV1Response,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_patient_consent(
        self,
        id: str,
        *,
        type: PatientConsentCreateV1RequestType,
        version: str,
        consented_at: dt.datetime,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PatientConsentCreateV1Response]:
        """
        Parameters
        ----------
        id : str

        type : PatientConsentCreateV1RequestType

        version : str
            The base document version that was agreed to, available at [Dashboard > Organization > Consent](https://app.usebridge.com/organization/consent) (eg, '2024-01-01')

        consented_at : dt.datetime

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PatientConsentCreateV1Response]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/patients/{encode_path_param(id)}/consent",
            method="POST",
            json={
                "type": type,
                "version": version,
                "consentedAt": consented_at,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PatientConsentCreateV1Response,
                    parse_obj_as(
                        type_=PatientConsentCreateV1Response,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawConsentClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_patient_consents(
        self,
        id: str,
        *,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PatientConsentsListV1Response]:
        """
        Parameters
        ----------
        id : str

        page : typing.Optional[int]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PatientConsentsListV1Response]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/patients/{encode_path_param(id)}/consent",
            method="GET",
            params={
                "page": page,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PatientConsentsListV1Response,
                    parse_obj_as(
                        type_=PatientConsentsListV1Response,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_patient_consent(
        self,
        id: str,
        *,
        type: PatientConsentCreateV1RequestType,
        version: str,
        consented_at: dt.datetime,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PatientConsentCreateV1Response]:
        """
        Parameters
        ----------
        id : str

        type : PatientConsentCreateV1RequestType

        version : str
            The base document version that was agreed to, available at [Dashboard > Organization > Consent](https://app.usebridge.com/organization/consent) (eg, '2024-01-01')

        consented_at : dt.datetime

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PatientConsentCreateV1Response]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/patients/{encode_path_param(id)}/consent",
            method="POST",
            json={
                "type": type,
                "version": version,
                "consentedAt": consented_at,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PatientConsentCreateV1Response,
                    parse_obj_as(
                        type_=PatientConsentCreateV1Response,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
