# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawPatientsClient, RawPatientsClient
from .types.patient_stream_v_1_response import PatientStreamV1Response
from .types.patient_update_v_1_request_address import PatientUpdateV1RequestAddress
from .types.patient_update_v_1_request_coverage import PatientUpdateV1RequestCoverage
from .types.patient_update_v_1_request_metadata import PatientUpdateV1RequestMetadata
from .types.patient_update_v_1_response import PatientUpdateV1Response
from .types.patients_list_v_1_response import PatientsListV1Response

if typing.TYPE_CHECKING:
    from .v_2.client import AsyncV2Client, V2Client
# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class PatientsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPatientsClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._v_2: typing.Optional[V2Client] = None

    @property
    def with_raw_response(self) -> RawPatientsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPatientsClient
        """
        return self._raw_client

    def stream_patient(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Iterator[PatientStreamV1Response]:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.Iterator[PatientStreamV1Response]

        Examples
        --------
        from rtaylor_205 import BridgeApiClient

        client = BridgeApiClient(
            api_key="YOUR_API_KEY",
        )
        response = client.patients.stream_patient(
            id="id",
        )
        for chunk in response:
            yield chunk
        """
        with self._raw_client.stream_patient(id, request_options=request_options) as r:
            yield from r.data

    def list_patients(
        self,
        *,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PatientsListV1Response:
        """
        Parameters
        ----------
        page : typing.Optional[int]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PatientsListV1Response

        Examples
        --------
        from rtaylor_205 import BridgeApiClient

        client = BridgeApiClient(
            api_key="YOUR_API_KEY",
        )
        client.patients.list_patients()
        """
        _response = self._raw_client.list_patients(page=page, limit=limit, request_options=request_options)
        return _response.data

    def update_patient(
        self,
        id: str,
        *,
        patient_token: typing.Optional[str] = OMIT,
        external_id: typing.Optional[str] = OMIT,
        coverage: typing.Optional[typing.Sequence[PatientUpdateV1RequestCoverage]] = OMIT,
        first_name: typing.Optional[str] = OMIT,
        last_name: typing.Optional[str] = OMIT,
        email: typing.Optional[str] = OMIT,
        date_of_birth: typing.Optional[dt.datetime] = OMIT,
        phone: typing.Optional[str] = OMIT,
        address: typing.Optional[PatientUpdateV1RequestAddress] = OMIT,
        metadata: typing.Optional[PatientUpdateV1RequestMetadata] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PatientUpdateV1Response:
        """
        Parameters
        ----------
        id : str

        patient_token : typing.Optional[str]

        external_id : typing.Optional[str]

        coverage : typing.Optional[typing.Sequence[PatientUpdateV1RequestCoverage]]
            Sets the active Policies to use for this Patient, applied to un-billed Services. In all cases, maximum of 1 element, secondary insurance does not need to be collected. For uninsured/cash-pay patients, set to an empty array.

        first_name : typing.Optional[str]

        last_name : typing.Optional[str]

        email : typing.Optional[str]

        date_of_birth : typing.Optional[dt.datetime]

        phone : typing.Optional[str]

        address : typing.Optional[PatientUpdateV1RequestAddress]

        metadata : typing.Optional[PatientUpdateV1RequestMetadata]
            Customizable object of string to string key-value data<br>Any modifications to this field will _overwrite_ the previous value

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PatientUpdateV1Response

        Examples
        --------
        from rtaylor_205 import BridgeApiClient

        client = BridgeApiClient(
            api_key="YOUR_API_KEY",
        )
        client.patients.update_patient(
            id="id",
        )
        """
        _response = self._raw_client.update_patient(
            id,
            patient_token=patient_token,
            external_id=external_id,
            coverage=coverage,
            first_name=first_name,
            last_name=last_name,
            email=email,
            date_of_birth=date_of_birth,
            phone=phone,
            address=address,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    def revalidate_patient(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from rtaylor_205 import BridgeApiClient

        client = BridgeApiClient(
            api_key="YOUR_API_KEY",
        )
        client.patients.revalidate_patient(
            id="id",
        )
        """
        _response = self._raw_client.revalidate_patient(id, request_options=request_options)
        return _response.data

    @property
    def v_2(self):
        if self._v_2 is None:
            from .v_2.client import V2Client  # noqa: E402

            self._v_2 = V2Client(client_wrapper=self._client_wrapper)
        return self._v_2


class AsyncPatientsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPatientsClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._v_2: typing.Optional[AsyncV2Client] = None

    @property
    def with_raw_response(self) -> AsyncRawPatientsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPatientsClient
        """
        return self._raw_client

    async def stream_patient(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.AsyncIterator[PatientStreamV1Response]:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.AsyncIterator[PatientStreamV1Response]

        Examples
        --------
        import asyncio

        from rtaylor_205 import AsyncBridgeApiClient

        client = AsyncBridgeApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.patients.stream_patient(
                id="id",
            )
            async for chunk in response:
                yield chunk


        asyncio.run(main())
        """
        async with self._raw_client.stream_patient(id, request_options=request_options) as r:
            async for _chunk in r.data:
                yield _chunk

    async def list_patients(
        self,
        *,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PatientsListV1Response:
        """
        Parameters
        ----------
        page : typing.Optional[int]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PatientsListV1Response

        Examples
        --------
        import asyncio

        from rtaylor_205 import AsyncBridgeApiClient

        client = AsyncBridgeApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.patients.list_patients()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_patients(page=page, limit=limit, request_options=request_options)
        return _response.data

    async def update_patient(
        self,
        id: str,
        *,
        patient_token: typing.Optional[str] = OMIT,
        external_id: typing.Optional[str] = OMIT,
        coverage: typing.Optional[typing.Sequence[PatientUpdateV1RequestCoverage]] = OMIT,
        first_name: typing.Optional[str] = OMIT,
        last_name: typing.Optional[str] = OMIT,
        email: typing.Optional[str] = OMIT,
        date_of_birth: typing.Optional[dt.datetime] = OMIT,
        phone: typing.Optional[str] = OMIT,
        address: typing.Optional[PatientUpdateV1RequestAddress] = OMIT,
        metadata: typing.Optional[PatientUpdateV1RequestMetadata] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PatientUpdateV1Response:
        """
        Parameters
        ----------
        id : str

        patient_token : typing.Optional[str]

        external_id : typing.Optional[str]

        coverage : typing.Optional[typing.Sequence[PatientUpdateV1RequestCoverage]]
            Sets the active Policies to use for this Patient, applied to un-billed Services. In all cases, maximum of 1 element, secondary insurance does not need to be collected. For uninsured/cash-pay patients, set to an empty array.

        first_name : typing.Optional[str]

        last_name : typing.Optional[str]

        email : typing.Optional[str]

        date_of_birth : typing.Optional[dt.datetime]

        phone : typing.Optional[str]

        address : typing.Optional[PatientUpdateV1RequestAddress]

        metadata : typing.Optional[PatientUpdateV1RequestMetadata]
            Customizable object of string to string key-value data<br>Any modifications to this field will _overwrite_ the previous value

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PatientUpdateV1Response

        Examples
        --------
        import asyncio

        from rtaylor_205 import AsyncBridgeApiClient

        client = AsyncBridgeApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.patients.update_patient(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_patient(
            id,
            patient_token=patient_token,
            external_id=external_id,
            coverage=coverage,
            first_name=first_name,
            last_name=last_name,
            email=email,
            date_of_birth=date_of_birth,
            phone=phone,
            address=address,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    async def revalidate_patient(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from rtaylor_205 import AsyncBridgeApiClient

        client = AsyncBridgeApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.patients.revalidate_patient(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.revalidate_patient(id, request_options=request_options)
        return _response.data

    @property
    def v_2(self):
        if self._v_2 is None:
            from .v_2.client import AsyncV2Client  # noqa: E402

            self._v_2 = AsyncV2Client(client_wrapper=self._client_wrapper)
        return self._v_2
