# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .service_create_v_2_request_location import ServiceCreateV2RequestLocation
from .service_create_v_2_request_metadata import ServiceCreateV2RequestMetadata
from .service_create_v_2_request_responsible_party import ServiceCreateV2RequestResponsibleParty
from .service_create_v_2_request_service_eligibility import ServiceCreateV2RequestServiceEligibility


class ServiceCreateV2Request(UniversalBaseModel):
    patient_id: typing_extensions.Annotated[str, FieldMetadata(alias="patientId"), pydantic.Field(alias="patientId")]
    date_of_service: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="dateOfService"),
        pydantic.Field(alias="dateOfService", description="Full ISO8601 timestamp, including timezone"),
    ]
    service_type_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="serviceTypeId"), pydantic.Field(alias="serviceTypeId")
    ]
    external_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="externalId"), pydantic.Field(alias="externalId")
    ] = None
    location: ServiceCreateV2RequestLocation = pydantic.Field()
    """
    Location of the Patient at the date of service, requires only the `state` value for telehealth
    """

    provider_id: typing_extensions.Annotated[str, FieldMetadata(alias="providerId"), pydantic.Field(alias="providerId")]
    service_eligibility: typing_extensions.Annotated[
        typing.Optional[ServiceCreateV2RequestServiceEligibility],
        FieldMetadata(alias="serviceEligibility"),
        pydantic.Field(alias="serviceEligibility"),
    ] = None
    prior_authorization_number: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="priorAuthorizationNumber"),
        pydantic.Field(alias="priorAuthorizationNumber"),
    ] = None
    metadata: typing.Optional[ServiceCreateV2RequestMetadata] = pydantic.Field(default=None)
    """
    Customizable object of string to string key-value data
    """

    responsible_party: typing_extensions.Annotated[
        typing.Optional[ServiceCreateV2RequestResponsibleParty],
        FieldMetadata(alias="responsibleParty"),
        pydantic.Field(alias="responsibleParty"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
