# This file was auto-generated by Fern from our API Definition.

import typing

ServiceCreateV2ResponsePatientResponsibilityFieldAmountFieldDeductibleType = typing.Union[
    typing.Literal["INDIVIDUAL", "FAMILY"], typing.Any
]
