# This file was auto-generated by Fern from our API Definition.

import typing

ServiceCancelV2ResponseStatus = typing.Union[
    typing.Literal["PENDING", "BILLING", "SETTLING", "COMPLETE", "TRIAGE", "CANCELED", "DENIED"], typing.Any
]
