# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .service_cancel_v_2_response_payments_element_type import ServiceCancelV2ResponsePaymentsElementType


class ServiceCancelV2ResponsePayment(UniversalBaseModel):
    id: str
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]
    service_id: typing_extensions.Annotated[str, FieldMetadata(alias="serviceId"), pydantic.Field(alias="serviceId")]
    paid_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="paidAt"), pydantic.Field(alias="paidAt")]
    transaction_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="transactionId"), pydantic.Field(alias="transactionId")
    ]
    type: ServiceCancelV2ResponsePaymentsElementType
    amount: int
    external_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="externalId"), pydantic.Field(alias="externalId")
    ] = None
    memo: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
