# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .service_update_v_2_request_location import ServiceUpdateV2RequestLocation
from .service_update_v_2_request_metadata import ServiceUpdateV2RequestMetadata
from .service_update_v_2_request_responsible_party import ServiceUpdateV2RequestResponsibleParty


class ServiceUpdateV2Request(UniversalBaseModel):
    patient_token: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="patientToken"), pydantic.Field(alias="patientToken")
    ] = None
    date_of_service: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="dateOfService"),
        pydantic.Field(alias="dateOfService", description="Full ISO8601 timestamp, including timezone"),
    ] = None
    service_type_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="serviceTypeId"), pydantic.Field(alias="serviceTypeId")
    ] = None
    location: typing.Optional[ServiceUpdateV2RequestLocation] = pydantic.Field(default=None)
    """
    Location of the Patient at the date of service, requires only the `state` value for telehealth
    """

    external_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="externalId"), pydantic.Field(alias="externalId")
    ] = None
    provider_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="providerId"), pydantic.Field(alias="providerId")
    ] = None
    prior_authorization_number: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="priorAuthorizationNumber"),
        pydantic.Field(alias="priorAuthorizationNumber"),
    ] = None
    responsible_party: typing_extensions.Annotated[
        typing.Optional[ServiceUpdateV2RequestResponsibleParty],
        FieldMetadata(alias="responsibleParty"),
        pydantic.Field(alias="responsibleParty"),
    ] = None
    metadata: typing.Optional[ServiceUpdateV2RequestMetadata] = pydantic.Field(default=None)
    """
    Customizable object of string to string key-value data<br>Any modifications to this field will _overwrite_ the previous value
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
