# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .patient_consents_list_v_1_response_item import PatientConsentsListV1ResponseItem


class PatientConsentsListV1Response(UniversalBaseModel):
    items: typing.List[PatientConsentsListV1ResponseItem] = pydantic.Field()
    """
    List results
    """

    count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total count (if available)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
