# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from . import healthie_patient, healthie_patients
    from .healthie_patient import (
        HealthiePatientGetHealthieClientV1Response,
        HealthiePatientGetHealthieClientV1ResponseAccount,
        HealthiePatientGetHealthieClientV1ResponseAccountFieldStatus,
        HealthiePatientGetHealthieClientV1ResponseAddress,
        HealthiePatientGetHealthieClientV1ResponseAddressFieldCountry,
        HealthiePatientGetHealthieClientV1ResponseAddressFieldState,
        HealthiePatientGetHealthieClientV1ResponseCoverage,
        HealthiePatientGetHealthieClientV1ResponseMetadata,
    )
    from .healthie_patients import (
        HealthiePatientEnsureHealthieClientV1Request,
        HealthiePatientEnsureHealthieClientV1Response,
        HealthiePatientEnsureHealthieClientV1ResponseAccount,
        HealthiePatientEnsureHealthieClientV1ResponseAccountFieldStatus,
        HealthiePatientEnsureHealthieClientV1ResponseAddress,
        HealthiePatientEnsureHealthieClientV1ResponseAddressFieldCountry,
        HealthiePatientEnsureHealthieClientV1ResponseAddressFieldState,
        HealthiePatientEnsureHealthieClientV1ResponseCoverage,
        HealthiePatientEnsureHealthieClientV1ResponseMetadata,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "HealthiePatientEnsureHealthieClientV1Request": ".healthie_patients",
    "HealthiePatientEnsureHealthieClientV1Response": ".healthie_patients",
    "HealthiePatientEnsureHealthieClientV1ResponseAccount": ".healthie_patients",
    "HealthiePatientEnsureHealthieClientV1ResponseAccountFieldStatus": ".healthie_patients",
    "HealthiePatientEnsureHealthieClientV1ResponseAddress": ".healthie_patients",
    "HealthiePatientEnsureHealthieClientV1ResponseAddressFieldCountry": ".healthie_patients",
    "HealthiePatientEnsureHealthieClientV1ResponseAddressFieldState": ".healthie_patients",
    "HealthiePatientEnsureHealthieClientV1ResponseCoverage": ".healthie_patients",
    "HealthiePatientEnsureHealthieClientV1ResponseMetadata": ".healthie_patients",
    "HealthiePatientGetHealthieClientV1Response": ".healthie_patient",
    "HealthiePatientGetHealthieClientV1ResponseAccount": ".healthie_patient",
    "HealthiePatientGetHealthieClientV1ResponseAccountFieldStatus": ".healthie_patient",
    "HealthiePatientGetHealthieClientV1ResponseAddress": ".healthie_patient",
    "HealthiePatientGetHealthieClientV1ResponseAddressFieldCountry": ".healthie_patient",
    "HealthiePatientGetHealthieClientV1ResponseAddressFieldState": ".healthie_patient",
    "HealthiePatientGetHealthieClientV1ResponseCoverage": ".healthie_patient",
    "HealthiePatientGetHealthieClientV1ResponseMetadata": ".healthie_patient",
    "healthie_patient": ".healthie_patient",
    "healthie_patients": ".healthie_patients",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "HealthiePatientEnsureHealthieClientV1Request",
    "HealthiePatientEnsureHealthieClientV1Response",
    "HealthiePatientEnsureHealthieClientV1ResponseAccount",
    "HealthiePatientEnsureHealthieClientV1ResponseAccountFieldStatus",
    "HealthiePatientEnsureHealthieClientV1ResponseAddress",
    "HealthiePatientEnsureHealthieClientV1ResponseAddressFieldCountry",
    "HealthiePatientEnsureHealthieClientV1ResponseAddressFieldState",
    "HealthiePatientEnsureHealthieClientV1ResponseCoverage",
    "HealthiePatientEnsureHealthieClientV1ResponseMetadata",
    "HealthiePatientGetHealthieClientV1Response",
    "HealthiePatientGetHealthieClientV1ResponseAccount",
    "HealthiePatientGetHealthieClientV1ResponseAccountFieldStatus",
    "HealthiePatientGetHealthieClientV1ResponseAddress",
    "HealthiePatientGetHealthieClientV1ResponseAddressFieldCountry",
    "HealthiePatientGetHealthieClientV1ResponseAddressFieldState",
    "HealthiePatientGetHealthieClientV1ResponseCoverage",
    "HealthiePatientGetHealthieClientV1ResponseMetadata",
    "healthie_patient",
    "healthie_patients",
]
