# This file was auto-generated by Fern from our API Definition.

import typing

PolicyStreamV1ResponseRelationship = typing.Union[
    typing.Literal["SELF", "CHILD", "SPOUSE", "OTHER", "NONE"], typing.Any
]
