# This file was auto-generated by Fern from our API Definition.

import typing

PolicyGetV1ResponseStatus = typing.Union[
    typing.Literal["PENDING", "UNKNOWN", "CONFIRMED", "REVALIDATING", "INVALID"], typing.Any
]
