# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .patient_update_v_1_request_address import PatientUpdateV1RequestAddress
from .patient_update_v_1_request_coverage import PatientUpdateV1RequestCoverage
from .patient_update_v_1_request_metadata import PatientUpdateV1RequestMetadata


class PatientUpdateV1Request(UniversalBaseModel):
    patient_token: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="patientToken"), pydantic.Field(alias="patientToken")
    ] = None
    external_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="externalId"), pydantic.Field(alias="externalId")
    ] = None
    coverage: typing.Optional[typing.List[PatientUpdateV1RequestCoverage]] = pydantic.Field(default=None)
    """
    Sets the active Policies to use for this Patient, applied to un-billed Services. In all cases, maximum of 1 element, secondary insurance does not need to be collected. For uninsured/cash-pay patients, set to an empty array.
    """

    first_name: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="firstName"), pydantic.Field(alias="firstName")
    ] = None
    last_name: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="lastName"), pydantic.Field(alias="lastName")
    ] = None
    email: typing.Optional[str] = None
    date_of_birth: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="dateOfBirth"), pydantic.Field(alias="dateOfBirth")
    ] = None
    phone: typing.Optional[str] = None
    address: typing.Optional[PatientUpdateV1RequestAddress] = None
    metadata: typing.Optional[PatientUpdateV1RequestMetadata] = pydantic.Field(default=None)
    """
    Customizable object of string to string key-value data<br>Any modifications to this field will _overwrite_ the previous value
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
