# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .patients_list_v_1_response_item_account import PatientsListV1ResponseItemAccount
from .patients_list_v_1_response_item_address import PatientsListV1ResponseItemAddress
from .patients_list_v_1_response_item_coverage import PatientsListV1ResponseItemCoverage
from .patients_list_v_1_response_item_metadata import PatientsListV1ResponseItemMetadata


class PatientsListV1ResponseItem(UniversalBaseModel):
    id: str
    patient_token: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="patientToken"), pydantic.Field(alias="patientToken")
    ] = None
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]
    external_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="externalId"), pydantic.Field(alias="externalId")
    ] = None
    coverage: typing.List[PatientsListV1ResponseItemCoverage]
    first_name: typing_extensions.Annotated[str, FieldMetadata(alias="firstName"), pydantic.Field(alias="firstName")]
    last_name: typing_extensions.Annotated[str, FieldMetadata(alias="lastName"), pydantic.Field(alias="lastName")]
    date_of_birth: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="dateOfBirth"), pydantic.Field(alias="dateOfBirth")
    ]
    email: str
    phone: typing.Optional[str] = None
    address: typing.Optional[PatientsListV1ResponseItemAddress] = None
    metadata: typing.Optional[PatientsListV1ResponseItemMetadata] = pydantic.Field(default=None)
    """
    Customizable object of string to string key-value data
    """

    account: typing.Optional[PatientsListV1ResponseItemAccount] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
