# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .patient_update_v_1_request_address_field_country import PatientUpdateV1RequestAddressFieldCountry
from .patient_update_v_1_request_address_field_state import PatientUpdateV1RequestAddressFieldState


class PatientUpdateV1RequestAddress(UniversalBaseModel):
    line_1: typing_extensions.Annotated[str, FieldMetadata(alias="line1"), pydantic.Field(alias="line1")]
    line_2: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="line2"), pydantic.Field(alias="line2")
    ] = None
    city: str
    state: PatientUpdateV1RequestAddressFieldState = pydantic.Field()
    """
    2 letter US state code
    """

    postal_code: typing_extensions.Annotated[str, FieldMetadata(alias="postalCode"), pydantic.Field(alias="postalCode")]
    country: typing.Optional[PatientUpdateV1RequestAddressFieldCountry] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
