# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .patient_consent_create_v_1_request_type import PatientConsentCreateV1RequestType


class PatientConsentCreateV1Request(UniversalBaseModel):
    type: PatientConsentCreateV1RequestType
    version: str = pydantic.Field()
    """
    The base document version that was agreed to, available at [Dashboard > Organization > Consent](https://app.usebridge.com/organization/consent) (eg, '2024-01-01')
    """

    consented_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="consentedAt"), pydantic.Field(alias="consentedAt")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
