# This file was auto-generated by Fern from our API Definition.

import typing

PatientConsentCreateV1RequestType = typing.Union[
    typing.Literal["ASSIGNMENT_OF_BENEFITS", "CONSENT_TO_TREAT", "PRIVACY_NOTICE"], typing.Any
]
