# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from .raw_client import AsyncRawEstimateChargesClient, RawEstimateChargesClient
from .types.estimate_charge_authorize_stripe_v_1_response import EstimateChargeAuthorizeStripeV1Response
from .types.estimate_charge_cancel_stripe_v_1_response import EstimateChargeCancelStripeV1Response
from .types.estimate_charge_capture_stripe_v_1_response import EstimateChargeCaptureStripeV1Response
from .types.estimate_charge_create_v_1_response import EstimateChargeCreateV1Response
from .types.estimate_charge_refund_stripe_v_1_response import EstimateChargeRefundStripeV1Response

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class EstimateChargesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawEstimateChargesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawEstimateChargesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawEstimateChargesClient
        """
        return self._raw_client

    def create_estimate_charge(
        self,
        *,
        patient_id: str,
        service_eligibility_id: str,
        external_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EstimateChargeCreateV1Response:
        """
        This endpoint can only be used after setting up the billing integration. Refer to the [billing integration documentation](/documentation/integrations/billing/overview) for more details.

        Parameters
        ----------
        patient_id : str

        service_eligibility_id : str

        external_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EstimateChargeCreateV1Response

        Examples
        --------
        from rtaylor_205 import BridgeApiClient

        client = BridgeApiClient(
            api_key="YOUR_API_KEY",
        )
        client.billing.estimate_charges.create_estimate_charge(
            patient_id="patientId",
            service_eligibility_id="serviceEligibilityId",
        )
        """
        _response = self._raw_client.create_estimate_charge(
            patient_id=patient_id,
            service_eligibility_id=service_eligibility_id,
            external_id=external_id,
            request_options=request_options,
        )
        return _response.data

    def authorize_stripe_estimate_charge(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EstimateChargeAuthorizeStripeV1Response:
        """
        This endpoint can only be used after setting up the billing integration. Refer to the [billing integration documentation](/documentation/integrations/billing/overview) for more details.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EstimateChargeAuthorizeStripeV1Response

        Examples
        --------
        from rtaylor_205 import BridgeApiClient

        client = BridgeApiClient(
            api_key="YOUR_API_KEY",
        )
        client.billing.estimate_charges.authorize_stripe_estimate_charge(
            id="id",
        )
        """
        _response = self._raw_client.authorize_stripe_estimate_charge(id, request_options=request_options)
        return _response.data

    def capture_stripe_estimate_charge(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EstimateChargeCaptureStripeV1Response:
        """
        This endpoint can only be used after setting up the billing integration. Refer to the [billing integration documentation](/documentation/integrations/billing/overview) for more details.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EstimateChargeCaptureStripeV1Response

        Examples
        --------
        from rtaylor_205 import BridgeApiClient

        client = BridgeApiClient(
            api_key="YOUR_API_KEY",
        )
        client.billing.estimate_charges.capture_stripe_estimate_charge(
            id="id",
        )
        """
        _response = self._raw_client.capture_stripe_estimate_charge(id, request_options=request_options)
        return _response.data

    def refund_stripe_estimate_charge(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EstimateChargeRefundStripeV1Response:
        """
        This endpoint can only be used after setting up the billing integration. Refer to the [billing integration documentation](/documentation/integrations/billing/overview) for more details.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EstimateChargeRefundStripeV1Response

        Examples
        --------
        from rtaylor_205 import BridgeApiClient

        client = BridgeApiClient(
            api_key="YOUR_API_KEY",
        )
        client.billing.estimate_charges.refund_stripe_estimate_charge(
            id="id",
        )
        """
        _response = self._raw_client.refund_stripe_estimate_charge(id, request_options=request_options)
        return _response.data

    def cancel_stripe_estimate_charge(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EstimateChargeCancelStripeV1Response:
        """
        This endpoint can only be used after setting up the billing integration. Refer to the [billing integration documentation](/documentation/integrations/billing/overview) for more details.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EstimateChargeCancelStripeV1Response

        Examples
        --------
        from rtaylor_205 import BridgeApiClient

        client = BridgeApiClient(
            api_key="YOUR_API_KEY",
        )
        client.billing.estimate_charges.cancel_stripe_estimate_charge(
            id="id",
        )
        """
        _response = self._raw_client.cancel_stripe_estimate_charge(id, request_options=request_options)
        return _response.data


class AsyncEstimateChargesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawEstimateChargesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawEstimateChargesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawEstimateChargesClient
        """
        return self._raw_client

    async def create_estimate_charge(
        self,
        *,
        patient_id: str,
        service_eligibility_id: str,
        external_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EstimateChargeCreateV1Response:
        """
        This endpoint can only be used after setting up the billing integration. Refer to the [billing integration documentation](/documentation/integrations/billing/overview) for more details.

        Parameters
        ----------
        patient_id : str

        service_eligibility_id : str

        external_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EstimateChargeCreateV1Response

        Examples
        --------
        import asyncio

        from rtaylor_205 import AsyncBridgeApiClient

        client = AsyncBridgeApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.billing.estimate_charges.create_estimate_charge(
                patient_id="patientId",
                service_eligibility_id="serviceEligibilityId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_estimate_charge(
            patient_id=patient_id,
            service_eligibility_id=service_eligibility_id,
            external_id=external_id,
            request_options=request_options,
        )
        return _response.data

    async def authorize_stripe_estimate_charge(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EstimateChargeAuthorizeStripeV1Response:
        """
        This endpoint can only be used after setting up the billing integration. Refer to the [billing integration documentation](/documentation/integrations/billing/overview) for more details.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EstimateChargeAuthorizeStripeV1Response

        Examples
        --------
        import asyncio

        from rtaylor_205 import AsyncBridgeApiClient

        client = AsyncBridgeApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.billing.estimate_charges.authorize_stripe_estimate_charge(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.authorize_stripe_estimate_charge(id, request_options=request_options)
        return _response.data

    async def capture_stripe_estimate_charge(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EstimateChargeCaptureStripeV1Response:
        """
        This endpoint can only be used after setting up the billing integration. Refer to the [billing integration documentation](/documentation/integrations/billing/overview) for more details.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EstimateChargeCaptureStripeV1Response

        Examples
        --------
        import asyncio

        from rtaylor_205 import AsyncBridgeApiClient

        client = AsyncBridgeApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.billing.estimate_charges.capture_stripe_estimate_charge(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.capture_stripe_estimate_charge(id, request_options=request_options)
        return _response.data

    async def refund_stripe_estimate_charge(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EstimateChargeRefundStripeV1Response:
        """
        This endpoint can only be used after setting up the billing integration. Refer to the [billing integration documentation](/documentation/integrations/billing/overview) for more details.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EstimateChargeRefundStripeV1Response

        Examples
        --------
        import asyncio

        from rtaylor_205 import AsyncBridgeApiClient

        client = AsyncBridgeApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.billing.estimate_charges.refund_stripe_estimate_charge(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.refund_stripe_estimate_charge(id, request_options=request_options)
        return _response.data

    async def cancel_stripe_estimate_charge(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EstimateChargeCancelStripeV1Response:
        """
        This endpoint can only be used after setting up the billing integration. Refer to the [billing integration documentation](/documentation/integrations/billing/overview) for more details.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EstimateChargeCancelStripeV1Response

        Examples
        --------
        import asyncio

        from rtaylor_205 import AsyncBridgeApiClient

        client = AsyncBridgeApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.billing.estimate_charges.cancel_stripe_estimate_charge(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cancel_stripe_estimate_charge(id, request_options=request_options)
        return _response.data
