# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .patient_stream_v_1_response import PatientStreamV1Response
    from .patient_stream_v_1_response_account import PatientStreamV1ResponseAccount
    from .patient_stream_v_1_response_account_field_status import PatientStreamV1ResponseAccountFieldStatus
    from .patient_stream_v_1_response_address import PatientStreamV1ResponseAddress
    from .patient_stream_v_1_response_address_field_country import PatientStreamV1ResponseAddressFieldCountry
    from .patient_stream_v_1_response_address_field_state import PatientStreamV1ResponseAddressFieldState
    from .patient_stream_v_1_response_coverage import PatientStreamV1ResponseCoverage
    from .patient_stream_v_1_response_metadata import PatientStreamV1ResponseMetadata
    from .patient_update_v_1_request import PatientUpdateV1Request
    from .patient_update_v_1_request_address import PatientUpdateV1RequestAddress
    from .patient_update_v_1_request_address_field_country import PatientUpdateV1RequestAddressFieldCountry
    from .patient_update_v_1_request_address_field_state import PatientUpdateV1RequestAddressFieldState
    from .patient_update_v_1_request_coverage import PatientUpdateV1RequestCoverage
    from .patient_update_v_1_request_metadata import PatientUpdateV1RequestMetadata
    from .patient_update_v_1_response import PatientUpdateV1Response
    from .patient_update_v_1_response_account import PatientUpdateV1ResponseAccount
    from .patient_update_v_1_response_account_field_status import PatientUpdateV1ResponseAccountFieldStatus
    from .patient_update_v_1_response_address import PatientUpdateV1ResponseAddress
    from .patient_update_v_1_response_address_field_country import PatientUpdateV1ResponseAddressFieldCountry
    from .patient_update_v_1_response_address_field_state import PatientUpdateV1ResponseAddressFieldState
    from .patient_update_v_1_response_coverage import PatientUpdateV1ResponseCoverage
    from .patient_update_v_1_response_metadata import PatientUpdateV1ResponseMetadata
    from .patients_list_v_1_response import PatientsListV1Response
    from .patients_list_v_1_response_item import PatientsListV1ResponseItem
    from .patients_list_v_1_response_item_account import PatientsListV1ResponseItemAccount
    from .patients_list_v_1_response_item_account_field_status import PatientsListV1ResponseItemAccountFieldStatus
    from .patients_list_v_1_response_item_address import PatientsListV1ResponseItemAddress
    from .patients_list_v_1_response_item_address_field_country import PatientsListV1ResponseItemAddressFieldCountry
    from .patients_list_v_1_response_item_address_field_state import PatientsListV1ResponseItemAddressFieldState
    from .patients_list_v_1_response_item_coverage import PatientsListV1ResponseItemCoverage
    from .patients_list_v_1_response_item_metadata import PatientsListV1ResponseItemMetadata
_dynamic_imports: typing.Dict[str, str] = {
    "PatientStreamV1Response": ".patient_stream_v_1_response",
    "PatientStreamV1ResponseAccount": ".patient_stream_v_1_response_account",
    "PatientStreamV1ResponseAccountFieldStatus": ".patient_stream_v_1_response_account_field_status",
    "PatientStreamV1ResponseAddress": ".patient_stream_v_1_response_address",
    "PatientStreamV1ResponseAddressFieldCountry": ".patient_stream_v_1_response_address_field_country",
    "PatientStreamV1ResponseAddressFieldState": ".patient_stream_v_1_response_address_field_state",
    "PatientStreamV1ResponseCoverage": ".patient_stream_v_1_response_coverage",
    "PatientStreamV1ResponseMetadata": ".patient_stream_v_1_response_metadata",
    "PatientUpdateV1Request": ".patient_update_v_1_request",
    "PatientUpdateV1RequestAddress": ".patient_update_v_1_request_address",
    "PatientUpdateV1RequestAddressFieldCountry": ".patient_update_v_1_request_address_field_country",
    "PatientUpdateV1RequestAddressFieldState": ".patient_update_v_1_request_address_field_state",
    "PatientUpdateV1RequestCoverage": ".patient_update_v_1_request_coverage",
    "PatientUpdateV1RequestMetadata": ".patient_update_v_1_request_metadata",
    "PatientUpdateV1Response": ".patient_update_v_1_response",
    "PatientUpdateV1ResponseAccount": ".patient_update_v_1_response_account",
    "PatientUpdateV1ResponseAccountFieldStatus": ".patient_update_v_1_response_account_field_status",
    "PatientUpdateV1ResponseAddress": ".patient_update_v_1_response_address",
    "PatientUpdateV1ResponseAddressFieldCountry": ".patient_update_v_1_response_address_field_country",
    "PatientUpdateV1ResponseAddressFieldState": ".patient_update_v_1_response_address_field_state",
    "PatientUpdateV1ResponseCoverage": ".patient_update_v_1_response_coverage",
    "PatientUpdateV1ResponseMetadata": ".patient_update_v_1_response_metadata",
    "PatientsListV1Response": ".patients_list_v_1_response",
    "PatientsListV1ResponseItem": ".patients_list_v_1_response_item",
    "PatientsListV1ResponseItemAccount": ".patients_list_v_1_response_item_account",
    "PatientsListV1ResponseItemAccountFieldStatus": ".patients_list_v_1_response_item_account_field_status",
    "PatientsListV1ResponseItemAddress": ".patients_list_v_1_response_item_address",
    "PatientsListV1ResponseItemAddressFieldCountry": ".patients_list_v_1_response_item_address_field_country",
    "PatientsListV1ResponseItemAddressFieldState": ".patients_list_v_1_response_item_address_field_state",
    "PatientsListV1ResponseItemCoverage": ".patients_list_v_1_response_item_coverage",
    "PatientsListV1ResponseItemMetadata": ".patients_list_v_1_response_item_metadata",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "PatientStreamV1Response",
    "PatientStreamV1ResponseAccount",
    "PatientStreamV1ResponseAccountFieldStatus",
    "PatientStreamV1ResponseAddress",
    "PatientStreamV1ResponseAddressFieldCountry",
    "PatientStreamV1ResponseAddressFieldState",
    "PatientStreamV1ResponseCoverage",
    "PatientStreamV1ResponseMetadata",
    "PatientUpdateV1Request",
    "PatientUpdateV1RequestAddress",
    "PatientUpdateV1RequestAddressFieldCountry",
    "PatientUpdateV1RequestAddressFieldState",
    "PatientUpdateV1RequestCoverage",
    "PatientUpdateV1RequestMetadata",
    "PatientUpdateV1Response",
    "PatientUpdateV1ResponseAccount",
    "PatientUpdateV1ResponseAccountFieldStatus",
    "PatientUpdateV1ResponseAddress",
    "PatientUpdateV1ResponseAddressFieldCountry",
    "PatientUpdateV1ResponseAddressFieldState",
    "PatientUpdateV1ResponseCoverage",
    "PatientUpdateV1ResponseMetadata",
    "PatientsListV1Response",
    "PatientsListV1ResponseItem",
    "PatientsListV1ResponseItemAccount",
    "PatientsListV1ResponseItemAccountFieldStatus",
    "PatientsListV1ResponseItemAddress",
    "PatientsListV1ResponseItemAddressFieldCountry",
    "PatientsListV1ResponseItemAddressFieldState",
    "PatientsListV1ResponseItemCoverage",
    "PatientsListV1ResponseItemMetadata",
]
