# This file was auto-generated by Fern from our API Definition.

from .service_cancel_v_2_response_service_type_field_provider_types_element import (
    ServiceCancelV2ResponseServiceTypeFieldProviderTypesElement,
)

ServiceCancelV2ResponseServiceTypeFieldProviderType = ServiceCancelV2ResponseServiceTypeFieldProviderTypesElement
