# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .service_create_v_2_response_service_eligibility_field_clinical_info import (
    ServiceCreateV2ResponseServiceEligibilityFieldClinicalInfo,
)
from .service_create_v_2_response_service_eligibility_field_conditional_patient_responsibility import (
    ServiceCreateV2ResponseServiceEligibilityFieldConditionalPatientResponsibility,
)
from .service_create_v_2_response_service_eligibility_field_message import (
    ServiceCreateV2ResponseServiceEligibilityFieldMessage,
)
from .service_create_v_2_response_service_eligibility_field_patient_responsibility import (
    ServiceCreateV2ResponseServiceEligibilityFieldPatientResponsibility,
)
from .service_create_v_2_response_service_eligibility_field_policy_id import (
    ServiceCreateV2ResponseServiceEligibilityFieldPolicyId,
)
from .service_create_v_2_response_service_eligibility_field_provider import (
    ServiceCreateV2ResponseServiceEligibilityFieldProvider,
)
from .service_create_v_2_response_service_eligibility_field_state import (
    ServiceCreateV2ResponseServiceEligibilityFieldState,
)
from .service_create_v_2_response_service_eligibility_field_status import (
    ServiceCreateV2ResponseServiceEligibilityFieldStatus,
)


class ServiceCreateV2ResponseServiceEligibility(UniversalBaseModel):
    id: str
    organization_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="organizationId"), pydantic.Field(alias="organizationId")
    ]
    validated_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="validatedAt"),
        pydantic.Field(alias="validatedAt", description="Timestamp this was executed"),
    ] = None
    service_type_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="serviceTypeId"), pydantic.Field(alias="serviceTypeId")
    ]
    date_of_service: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="dateOfService"), pydantic.Field(alias="dateOfService")
    ]
    status: ServiceCreateV2ResponseServiceEligibilityFieldStatus
    patient_responsibility: typing_extensions.Annotated[
        typing.Optional[ServiceCreateV2ResponseServiceEligibilityFieldPatientResponsibility],
        FieldMetadata(alias="patientResponsibility"),
        pydantic.Field(
            alias="patientResponsibility",
            description="Describes the Patient Responsibility. All dollar values are in USD cents ($15 = 1500). The 'total' is the amount that the patient owes. The breakdown are in non-oop fields. The oop fields apply when the patient has hit (or will hit) their OOP limits.",
        ),
    ] = None
    providers: typing.List[ServiceCreateV2ResponseServiceEligibilityFieldProvider]
    policy_ids: typing_extensions.Annotated[
        typing.List[ServiceCreateV2ResponseServiceEligibilityFieldPolicyId],
        FieldMetadata(alias="policyIds"),
        pydantic.Field(alias="policyIds"),
    ]
    state: ServiceCreateV2ResponseServiceEligibilityFieldState = pydantic.Field()
    """
    2 letter US state code
    """

    messages: typing.Optional[typing.List[ServiceCreateV2ResponseServiceEligibilityFieldMessage]] = None
    clinical_info: typing_extensions.Annotated[
        typing.Optional[ServiceCreateV2ResponseServiceEligibilityFieldClinicalInfo],
        FieldMetadata(alias="clinicalInfo"),
        pydantic.Field(alias="clinicalInfo"),
    ] = None
    conditional_patient_responsibilities: typing_extensions.Annotated[
        typing.Optional[typing.List[ServiceCreateV2ResponseServiceEligibilityFieldConditionalPatientResponsibility]],
        FieldMetadata(alias="conditionalPatientResponsibilities"),
        pydantic.Field(alias="conditionalPatientResponsibilities"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
