# This file was auto-generated by Fern from our API Definition.

import typing

ServiceCancelV2ResponsePatientResponsibilityFieldStatus = typing.Union[
    typing.Literal["UNKNOWN", "ESTIMATE", "FINALIZED"], typing.Any
]
