# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from .raw_client import AsyncRawHealthClient, RawHealthClient
from .types.health_events_list_v_1_order_event_at import HealthEventsListV1OrderEventAt
from .types.health_events_list_v_1_response import HealthEventsListV1Response


class HealthClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawHealthClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawHealthClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawHealthClient
        """
        return self._raw_client

    def list_health_events(
        self,
        id: str,
        *,
        order_event_at: typing.Optional[HealthEventsListV1OrderEventAt] = None,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HealthEventsListV1Response:
        """
        Parameters
        ----------
        id : str
            Payer group ID or slug (both are supported)

        order_event_at : typing.Optional[HealthEventsListV1OrderEventAt]

        page : typing.Optional[int]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HealthEventsListV1Response

        Examples
        --------
        from usebridge_api import BridgeApiClient

        client = BridgeApiClient(
            api_key="YOUR_API_KEY",
        )
        client.payer_groups.health.list_health_events(
            id="id",
        )
        """
        _response = self._raw_client.list_health_events(
            id, order_event_at=order_event_at, page=page, limit=limit, request_options=request_options
        )
        return _response.data


class AsyncHealthClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawHealthClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawHealthClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawHealthClient
        """
        return self._raw_client

    async def list_health_events(
        self,
        id: str,
        *,
        order_event_at: typing.Optional[HealthEventsListV1OrderEventAt] = None,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HealthEventsListV1Response:
        """
        Parameters
        ----------
        id : str
            Payer group ID or slug (both are supported)

        order_event_at : typing.Optional[HealthEventsListV1OrderEventAt]

        page : typing.Optional[int]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HealthEventsListV1Response

        Examples
        --------
        import asyncio

        from usebridge_api import AsyncBridgeApiClient

        client = AsyncBridgeApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.payer_groups.health.list_health_events(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_health_events(
            id, order_event_at=order_event_at, page=page, limit=limit, request_options=request_options
        )
        return _response.data
