# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .service_eligibility_create_v_2_request import ServiceEligibilityCreateV2Request
    from .service_eligibility_create_v_2_request_clinical_info import ServiceEligibilityCreateV2RequestClinicalInfo
    from .service_eligibility_create_v_2_request_clinical_info_field_diagnosis import (
        ServiceEligibilityCreateV2RequestClinicalInfoFieldDiagnosis,
    )
    from .service_eligibility_create_v_2_request_policy_id import ServiceEligibilityCreateV2RequestPolicyId
    from .service_eligibility_create_v_2_request_state import ServiceEligibilityCreateV2RequestState
    from .service_eligibility_create_v_2_response import ServiceEligibilityCreateV2Response
    from .service_eligibility_create_v_2_response_clinical_info import ServiceEligibilityCreateV2ResponseClinicalInfo
    from .service_eligibility_create_v_2_response_clinical_info_field_diagnosis import (
        ServiceEligibilityCreateV2ResponseClinicalInfoFieldDiagnosis,
    )
    from .service_eligibility_create_v_2_response_conditional_patient_responsibilities_element_condition import (
        ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementCondition,
    )
    from .service_eligibility_create_v_2_response_conditional_patient_responsibilities_element_conditions_element_diagnosis import (
        ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementConditionsElementDiagnosis,
    )
    from .service_eligibility_create_v_2_response_conditional_patient_responsibilities_element_limit import (
        ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementLimit,
    )
    from .service_eligibility_create_v_2_response_conditional_patient_responsibilities_element_limit_field_metric import (
        ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementLimitFieldMetric,
    )
    from .service_eligibility_create_v_2_response_conditional_patient_responsibilities_element_limit_field_period import (
        ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementLimitFieldPeriod,
    )
    from .service_eligibility_create_v_2_response_conditional_patient_responsibilities_element_limit_field_type import (
        ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementLimitFieldType,
    )
    from .service_eligibility_create_v_2_response_conditional_patient_responsibilities_element_limit_field_units import (
        ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementLimitFieldUnits,
    )
    from .service_eligibility_create_v_2_response_conditional_patient_responsibilities_element_patient_responsibility import (
        ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementPatientResponsibility,
    )
    from .service_eligibility_create_v_2_response_conditional_patient_responsibilities_element_patient_responsibility_field_deductible_type import (
        ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementPatientResponsibilityFieldDeductibleType,
    )
    from .service_eligibility_create_v_2_response_conditional_patient_responsibility import (
        ServiceEligibilityCreateV2ResponseConditionalPatientResponsibility,
    )
    from .service_eligibility_create_v_2_response_message import ServiceEligibilityCreateV2ResponseMessage
    from .service_eligibility_create_v_2_response_patient_responsibility import (
        ServiceEligibilityCreateV2ResponsePatientResponsibility,
    )
    from .service_eligibility_create_v_2_response_patient_responsibility_field_deductible_type import (
        ServiceEligibilityCreateV2ResponsePatientResponsibilityFieldDeductibleType,
    )
    from .service_eligibility_create_v_2_response_policy_id import ServiceEligibilityCreateV2ResponsePolicyId
    from .service_eligibility_create_v_2_response_provider import ServiceEligibilityCreateV2ResponseProvider
    from .service_eligibility_create_v_2_response_providers_element_type import (
        ServiceEligibilityCreateV2ResponseProvidersElementType,
    )
    from .service_eligibility_create_v_2_response_state import ServiceEligibilityCreateV2ResponseState
    from .service_eligibility_create_v_2_response_status import ServiceEligibilityCreateV2ResponseStatus
_dynamic_imports: typing.Dict[str, str] = {
    "ServiceEligibilityCreateV2Request": ".service_eligibility_create_v_2_request",
    "ServiceEligibilityCreateV2RequestClinicalInfo": ".service_eligibility_create_v_2_request_clinical_info",
    "ServiceEligibilityCreateV2RequestClinicalInfoFieldDiagnosis": ".service_eligibility_create_v_2_request_clinical_info_field_diagnosis",
    "ServiceEligibilityCreateV2RequestPolicyId": ".service_eligibility_create_v_2_request_policy_id",
    "ServiceEligibilityCreateV2RequestState": ".service_eligibility_create_v_2_request_state",
    "ServiceEligibilityCreateV2Response": ".service_eligibility_create_v_2_response",
    "ServiceEligibilityCreateV2ResponseClinicalInfo": ".service_eligibility_create_v_2_response_clinical_info",
    "ServiceEligibilityCreateV2ResponseClinicalInfoFieldDiagnosis": ".service_eligibility_create_v_2_response_clinical_info_field_diagnosis",
    "ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementCondition": ".service_eligibility_create_v_2_response_conditional_patient_responsibilities_element_condition",
    "ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementConditionsElementDiagnosis": ".service_eligibility_create_v_2_response_conditional_patient_responsibilities_element_conditions_element_diagnosis",
    "ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementLimit": ".service_eligibility_create_v_2_response_conditional_patient_responsibilities_element_limit",
    "ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementLimitFieldMetric": ".service_eligibility_create_v_2_response_conditional_patient_responsibilities_element_limit_field_metric",
    "ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementLimitFieldPeriod": ".service_eligibility_create_v_2_response_conditional_patient_responsibilities_element_limit_field_period",
    "ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementLimitFieldType": ".service_eligibility_create_v_2_response_conditional_patient_responsibilities_element_limit_field_type",
    "ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementLimitFieldUnits": ".service_eligibility_create_v_2_response_conditional_patient_responsibilities_element_limit_field_units",
    "ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementPatientResponsibility": ".service_eligibility_create_v_2_response_conditional_patient_responsibilities_element_patient_responsibility",
    "ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementPatientResponsibilityFieldDeductibleType": ".service_eligibility_create_v_2_response_conditional_patient_responsibilities_element_patient_responsibility_field_deductible_type",
    "ServiceEligibilityCreateV2ResponseConditionalPatientResponsibility": ".service_eligibility_create_v_2_response_conditional_patient_responsibility",
    "ServiceEligibilityCreateV2ResponseMessage": ".service_eligibility_create_v_2_response_message",
    "ServiceEligibilityCreateV2ResponsePatientResponsibility": ".service_eligibility_create_v_2_response_patient_responsibility",
    "ServiceEligibilityCreateV2ResponsePatientResponsibilityFieldDeductibleType": ".service_eligibility_create_v_2_response_patient_responsibility_field_deductible_type",
    "ServiceEligibilityCreateV2ResponsePolicyId": ".service_eligibility_create_v_2_response_policy_id",
    "ServiceEligibilityCreateV2ResponseProvider": ".service_eligibility_create_v_2_response_provider",
    "ServiceEligibilityCreateV2ResponseProvidersElementType": ".service_eligibility_create_v_2_response_providers_element_type",
    "ServiceEligibilityCreateV2ResponseState": ".service_eligibility_create_v_2_response_state",
    "ServiceEligibilityCreateV2ResponseStatus": ".service_eligibility_create_v_2_response_status",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ServiceEligibilityCreateV2Request",
    "ServiceEligibilityCreateV2RequestClinicalInfo",
    "ServiceEligibilityCreateV2RequestClinicalInfoFieldDiagnosis",
    "ServiceEligibilityCreateV2RequestPolicyId",
    "ServiceEligibilityCreateV2RequestState",
    "ServiceEligibilityCreateV2Response",
    "ServiceEligibilityCreateV2ResponseClinicalInfo",
    "ServiceEligibilityCreateV2ResponseClinicalInfoFieldDiagnosis",
    "ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementCondition",
    "ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementConditionsElementDiagnosis",
    "ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementLimit",
    "ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementLimitFieldMetric",
    "ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementLimitFieldPeriod",
    "ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementLimitFieldType",
    "ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementLimitFieldUnits",
    "ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementPatientResponsibility",
    "ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementPatientResponsibilityFieldDeductibleType",
    "ServiceEligibilityCreateV2ResponseConditionalPatientResponsibility",
    "ServiceEligibilityCreateV2ResponseMessage",
    "ServiceEligibilityCreateV2ResponsePatientResponsibility",
    "ServiceEligibilityCreateV2ResponsePatientResponsibilityFieldDeductibleType",
    "ServiceEligibilityCreateV2ResponsePolicyId",
    "ServiceEligibilityCreateV2ResponseProvider",
    "ServiceEligibilityCreateV2ResponseProvidersElementType",
    "ServiceEligibilityCreateV2ResponseState",
    "ServiceEligibilityCreateV2ResponseStatus",
]
