# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .service_eligibility_create_v_2_response_conditional_patient_responsibilities_element_limit_field_metric import (
    ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementLimitFieldMetric,
)
from .service_eligibility_create_v_2_response_conditional_patient_responsibilities_element_limit_field_period import (
    ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementLimitFieldPeriod,
)
from .service_eligibility_create_v_2_response_conditional_patient_responsibilities_element_limit_field_type import (
    ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementLimitFieldType,
)
from .service_eligibility_create_v_2_response_conditional_patient_responsibilities_element_limit_field_units import (
    ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementLimitFieldUnits,
)


class ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementLimit(UniversalBaseModel):
    type: ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementLimitFieldType
    value: typing.Optional[int] = None
    metric: typing.Optional[
        ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementLimitFieldMetric
    ] = None
    period: typing.Optional[
        ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementLimitFieldPeriod
    ] = None
    units: typing.Optional[
        ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementLimitFieldUnits
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
