# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        PolicyGetV1Response,
        PolicyGetV1ResponseError,
        PolicyGetV1ResponseLatest,
        PolicyGetV1ResponsePayer,
        PolicyGetV1ResponsePerson,
        PolicyGetV1ResponsePolicyHolder,
        PolicyGetV1ResponseRelationship,
        PolicyGetV1ResponseState,
        PolicyGetV1ResponseStatus,
        PolicyStreamV1Response,
        PolicyStreamV1ResponseError,
        PolicyStreamV1ResponseLatest,
        PolicyStreamV1ResponsePayer,
        PolicyStreamV1ResponsePerson,
        PolicyStreamV1ResponsePolicyHolder,
        PolicyStreamV1ResponseRelationship,
        PolicyStreamV1ResponseState,
        PolicyStreamV1ResponseStatus,
    )
    from . import v_2
    from .v_2 import (
        PolicyCreateV2Request,
        PolicyCreateV2RequestPerson,
        PolicyCreateV2RequestState,
        PolicyCreateV2Response,
        PolicyCreateV2ResponseError,
        PolicyCreateV2ResponseLatest,
        PolicyCreateV2ResponsePayer,
        PolicyCreateV2ResponsePerson,
        PolicyCreateV2ResponsePolicyHolder,
        PolicyCreateV2ResponseRelationship,
        PolicyCreateV2ResponseState,
        PolicyCreateV2ResponseStatus,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "PolicyCreateV2Request": ".v_2",
    "PolicyCreateV2RequestPerson": ".v_2",
    "PolicyCreateV2RequestState": ".v_2",
    "PolicyCreateV2Response": ".v_2",
    "PolicyCreateV2ResponseError": ".v_2",
    "PolicyCreateV2ResponseLatest": ".v_2",
    "PolicyCreateV2ResponsePayer": ".v_2",
    "PolicyCreateV2ResponsePerson": ".v_2",
    "PolicyCreateV2ResponsePolicyHolder": ".v_2",
    "PolicyCreateV2ResponseRelationship": ".v_2",
    "PolicyCreateV2ResponseState": ".v_2",
    "PolicyCreateV2ResponseStatus": ".v_2",
    "PolicyGetV1Response": ".types",
    "PolicyGetV1ResponseError": ".types",
    "PolicyGetV1ResponseLatest": ".types",
    "PolicyGetV1ResponsePayer": ".types",
    "PolicyGetV1ResponsePerson": ".types",
    "PolicyGetV1ResponsePolicyHolder": ".types",
    "PolicyGetV1ResponseRelationship": ".types",
    "PolicyGetV1ResponseState": ".types",
    "PolicyGetV1ResponseStatus": ".types",
    "PolicyStreamV1Response": ".types",
    "PolicyStreamV1ResponseError": ".types",
    "PolicyStreamV1ResponseLatest": ".types",
    "PolicyStreamV1ResponsePayer": ".types",
    "PolicyStreamV1ResponsePerson": ".types",
    "PolicyStreamV1ResponsePolicyHolder": ".types",
    "PolicyStreamV1ResponseRelationship": ".types",
    "PolicyStreamV1ResponseState": ".types",
    "PolicyStreamV1ResponseStatus": ".types",
    "v_2": ".v_2",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "PolicyCreateV2Request",
    "PolicyCreateV2RequestPerson",
    "PolicyCreateV2RequestState",
    "PolicyCreateV2Response",
    "PolicyCreateV2ResponseError",
    "PolicyCreateV2ResponseLatest",
    "PolicyCreateV2ResponsePayer",
    "PolicyCreateV2ResponsePerson",
    "PolicyCreateV2ResponsePolicyHolder",
    "PolicyCreateV2ResponseRelationship",
    "PolicyCreateV2ResponseState",
    "PolicyCreateV2ResponseStatus",
    "PolicyGetV1Response",
    "PolicyGetV1ResponseError",
    "PolicyGetV1ResponseLatest",
    "PolicyGetV1ResponsePayer",
    "PolicyGetV1ResponsePerson",
    "PolicyGetV1ResponsePolicyHolder",
    "PolicyGetV1ResponseRelationship",
    "PolicyGetV1ResponseState",
    "PolicyGetV1ResponseStatus",
    "PolicyStreamV1Response",
    "PolicyStreamV1ResponseError",
    "PolicyStreamV1ResponseLatest",
    "PolicyStreamV1ResponsePayer",
    "PolicyStreamV1ResponsePerson",
    "PolicyStreamV1ResponsePolicyHolder",
    "PolicyStreamV1ResponseRelationship",
    "PolicyStreamV1ResponseState",
    "PolicyStreamV1ResponseStatus",
    "v_2",
]
