# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .fee_capture_stripe_v_1_response import FeeCaptureStripeV1Response
    from .fee_capture_stripe_v_1_response_status import FeeCaptureStripeV1ResponseStatus
    from .fee_capture_stripe_v_1_response_stripe import FeeCaptureStripeV1ResponseStripe
    from .fee_capture_stripe_v_1_response_type import FeeCaptureStripeV1ResponseType
    from .fee_create_v_1_request import FeeCreateV1Request
    from .fee_create_v_1_request_type import FeeCreateV1RequestType
    from .fee_create_v_1_response import FeeCreateV1Response
    from .fee_create_v_1_response_status import FeeCreateV1ResponseStatus
    from .fee_create_v_1_response_type import FeeCreateV1ResponseType
    from .fee_refund_stripe_v_1_response import FeeRefundStripeV1Response
    from .fee_refund_stripe_v_1_response_status import FeeRefundStripeV1ResponseStatus
    from .fee_refund_stripe_v_1_response_stripe import FeeRefundStripeV1ResponseStripe
    from .fee_refund_stripe_v_1_response_type import FeeRefundStripeV1ResponseType
_dynamic_imports: typing.Dict[str, str] = {
    "FeeCaptureStripeV1Response": ".fee_capture_stripe_v_1_response",
    "FeeCaptureStripeV1ResponseStatus": ".fee_capture_stripe_v_1_response_status",
    "FeeCaptureStripeV1ResponseStripe": ".fee_capture_stripe_v_1_response_stripe",
    "FeeCaptureStripeV1ResponseType": ".fee_capture_stripe_v_1_response_type",
    "FeeCreateV1Request": ".fee_create_v_1_request",
    "FeeCreateV1RequestType": ".fee_create_v_1_request_type",
    "FeeCreateV1Response": ".fee_create_v_1_response",
    "FeeCreateV1ResponseStatus": ".fee_create_v_1_response_status",
    "FeeCreateV1ResponseType": ".fee_create_v_1_response_type",
    "FeeRefundStripeV1Response": ".fee_refund_stripe_v_1_response",
    "FeeRefundStripeV1ResponseStatus": ".fee_refund_stripe_v_1_response_status",
    "FeeRefundStripeV1ResponseStripe": ".fee_refund_stripe_v_1_response_stripe",
    "FeeRefundStripeV1ResponseType": ".fee_refund_stripe_v_1_response_type",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "FeeCaptureStripeV1Response",
    "FeeCaptureStripeV1ResponseStatus",
    "FeeCaptureStripeV1ResponseStripe",
    "FeeCaptureStripeV1ResponseType",
    "FeeCreateV1Request",
    "FeeCreateV1RequestType",
    "FeeCreateV1Response",
    "FeeCreateV1ResponseStatus",
    "FeeCreateV1ResponseType",
    "FeeRefundStripeV1Response",
    "FeeRefundStripeV1ResponseStatus",
    "FeeRefundStripeV1ResponseStripe",
    "FeeRefundStripeV1ResponseType",
]
