# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .fee_create_v_1_request_type import FeeCreateV1RequestType


class FeeCreateV1Request(UniversalBaseModel):
    patient_id: typing_extensions.Annotated[str, FieldMetadata(alias="patientId"), pydantic.Field(alias="patientId")]
    service_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="serviceId"), pydantic.Field(alias="serviceId")
    ] = None
    external_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="externalId"), pydantic.Field(alias="externalId")
    ] = None
    type: FeeCreateV1RequestType
    amount: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
