# This file was auto-generated by Fern from our API Definition.

import typing

FeeCaptureStripeV1ResponseStatus = typing.Union[
    typing.Literal["PENDING", "CAPTURING", "PAID", "VOIDED", "PARTIALLY_REFUNDED", "REFUNDED"], typing.Any
]
