# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from .raw_client import AsyncRawEnrollmentClient, RawEnrollmentClient
from .types.provider_enrollment_status_get_v_1_response import ProviderEnrollmentStatusGetV1Response


class EnrollmentClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawEnrollmentClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawEnrollmentClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawEnrollmentClient
        """
        return self._raw_client

    def get_provider_enrollment_status(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ProviderEnrollmentStatusGetV1Response:
        """
        Returns the high-level enrollment status of a provider

        **Production only:** This endpoint is only available in Production and will not work in Sandbox.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProviderEnrollmentStatusGetV1Response

        Examples
        --------
        from rtaylor_205 import BridgeApiClient

        client = BridgeApiClient(
            api_key="YOUR_API_KEY",
        )
        client.providers.enrollment.get_provider_enrollment_status(
            id="id",
        )
        """
        _response = self._raw_client.get_provider_enrollment_status(id, request_options=request_options)
        return _response.data


class AsyncEnrollmentClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawEnrollmentClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawEnrollmentClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawEnrollmentClient
        """
        return self._raw_client

    async def get_provider_enrollment_status(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ProviderEnrollmentStatusGetV1Response:
        """
        Returns the high-level enrollment status of a provider

        **Production only:** This endpoint is only available in Production and will not work in Sandbox.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProviderEnrollmentStatusGetV1Response

        Examples
        --------
        import asyncio

        from rtaylor_205 import AsyncBridgeApiClient

        client = AsyncBridgeApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.providers.enrollment.get_provider_enrollment_status(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_provider_enrollment_status(id, request_options=request_options)
        return _response.data
