# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from .raw_client import AsyncRawHealthiePatientsClient, RawHealthiePatientsClient
from .types.healthie_patient_ensure_healthie_client_v_1_response import HealthiePatientEnsureHealthieClientV1Response

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class HealthiePatientsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawHealthiePatientsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawHealthiePatientsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawHealthiePatientsClient
        """
        return self._raw_client

    def ensure_healthie_client_healthie_patient(
        self, *, healthie_client_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HealthiePatientEnsureHealthieClientV1Response:
        """
        Resolves or syncs a Bridge Patient for a Healthie client id. Returns the same shape as Patient create (including a fresh patient token).

        Parameters
        ----------
        healthie_client_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HealthiePatientEnsureHealthieClientV1Response

        Examples
        --------
        from usebridge_api import BridgeApiClient

        client = BridgeApiClient(
            api_key="YOUR_API_KEY",
        )
        client.integrations.healthie_patients.ensure_healthie_client_healthie_patient(
            healthie_client_id="healthieClientId",
        )
        """
        _response = self._raw_client.ensure_healthie_client_healthie_patient(
            healthie_client_id=healthie_client_id, request_options=request_options
        )
        return _response.data


class AsyncHealthiePatientsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawHealthiePatientsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawHealthiePatientsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawHealthiePatientsClient
        """
        return self._raw_client

    async def ensure_healthie_client_healthie_patient(
        self, *, healthie_client_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HealthiePatientEnsureHealthieClientV1Response:
        """
        Resolves or syncs a Bridge Patient for a Healthie client id. Returns the same shape as Patient create (including a fresh patient token).

        Parameters
        ----------
        healthie_client_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HealthiePatientEnsureHealthieClientV1Response

        Examples
        --------
        import asyncio

        from usebridge_api import AsyncBridgeApiClient

        client = AsyncBridgeApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.integrations.healthie_patients.ensure_healthie_client_healthie_patient(
                healthie_client_id="healthieClientId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.ensure_healthie_client_healthie_patient(
            healthie_client_id=healthie_client_id, request_options=request_options
        )
        return _response.data
