# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .service_get_v_1_response_service_eligibility_field_conditional_patient_responsibilities_element_conditions_element_diagnosis import (
    ServiceGetV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementConditionsElementDiagnosis,
)


class ServiceGetV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementCondition(UniversalBaseModel):
    diagnoses: typing.Optional[
        typing.List[
            ServiceGetV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementConditionsElementDiagnosis
        ]
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
