# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .service_get_v_1_response_patient_responsibility_field_amount import (
    ServiceGetV1ResponsePatientResponsibilityFieldAmount,
)
from .service_get_v_1_response_patient_responsibility_field_status import (
    ServiceGetV1ResponsePatientResponsibilityFieldStatus,
)


class ServiceGetV1ResponsePatientResponsibility(UniversalBaseModel):
    amount: typing.Optional[ServiceGetV1ResponsePatientResponsibilityFieldAmount] = pydantic.Field(default=None)
    """
    The most-current patient responsibility, either estimate or finalized amounts
    """

    status: typing.Optional[ServiceGetV1ResponsePatientResponsibilityFieldStatus] = pydantic.Field(default=None)
    """
    The status of the `amount` value. `UNKNOWN` if this is not determinable, `ESTIMATE` until claims are settled, `FINALIZED` when the claims are settled.
    """

    paid: typing.Optional[int] = pydantic.Field(default=None)
    """
    The amount (USD cents) of patient responsibility that has been paid, equal to the sum of all Payments.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
