# This file was auto-generated by Fern from our API Definition.

import typing

ServiceGetV1ResponseServiceEligibilityFieldProvidersElementType = typing.Union[
    typing.Literal["MD", "NP", "DO", "ND", "AP", "OT", "LCSW", "RN", "CN", "CWC", "CM", "PA", "RDN", "PT"], typing.Any
]
