# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .services_list_v_1_response_item_service_eligibility_field_conditional_patient_responsibilities_element_condition import (
    ServicesListV1ResponseItemServiceEligibilityFieldConditionalPatientResponsibilitiesElementCondition,
)
from .services_list_v_1_response_item_service_eligibility_field_conditional_patient_responsibilities_element_limit import (
    ServicesListV1ResponseItemServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimit,
)
from .services_list_v_1_response_item_service_eligibility_field_conditional_patient_responsibilities_element_patient_responsibility import (
    ServicesListV1ResponseItemServiceEligibilityFieldConditionalPatientResponsibilitiesElementPatientResponsibility,
)


class ServicesListV1ResponseItemServiceEligibilityFieldConditionalPatientResponsibility(UniversalBaseModel):
    conditions: typing.List[
        ServicesListV1ResponseItemServiceEligibilityFieldConditionalPatientResponsibilitiesElementCondition
    ]
    limit: ServicesListV1ResponseItemServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimit
    patient_responsibility: typing_extensions.Annotated[
        ServicesListV1ResponseItemServiceEligibilityFieldConditionalPatientResponsibilitiesElementPatientResponsibility,
        FieldMetadata(alias="patientResponsibility"),
        pydantic.Field(
            alias="patientResponsibility",
            description="Describes the Patient Responsibility. All dollar values are in USD cents ($15 = 1500). The 'total' is the amount that the patient owes. The breakdown are in non-oop fields. The oop fields apply when the patient has hit (or will hit) their OOP limits.",
        ),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
