# This file was auto-generated by Fern from our API Definition.

import typing

ServiceStreamV1ResponseServiceTypeFieldPlaceOfService = typing.Union[
    typing.Literal["TELEHEALTH_HOME", "TELEHEALTH_NOT_HOME", "OFFICE"], typing.Any
]
