# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .service_stream_v_1_response_cancellation_reason import ServiceStreamV1ResponseCancellationReason
from .service_stream_v_1_response_claim_status import ServiceStreamV1ResponseClaimStatus
from .service_stream_v_1_response_coverage_status import ServiceStreamV1ResponseCoverageStatus
from .service_stream_v_1_response_location import ServiceStreamV1ResponseLocation
from .service_stream_v_1_response_metadata import ServiceStreamV1ResponseMetadata
from .service_stream_v_1_response_patient_responsibility import ServiceStreamV1ResponsePatientResponsibility
from .service_stream_v_1_response_payment import ServiceStreamV1ResponsePayment
from .service_stream_v_1_response_provider import ServiceStreamV1ResponseProvider
from .service_stream_v_1_response_responsible_party import ServiceStreamV1ResponseResponsibleParty
from .service_stream_v_1_response_service_eligibility import ServiceStreamV1ResponseServiceEligibility
from .service_stream_v_1_response_service_type import ServiceStreamV1ResponseServiceType
from .service_stream_v_1_response_status import ServiceStreamV1ResponseStatus
from .service_stream_v_1_response_task import ServiceStreamV1ResponseTask


class ServiceStreamV1Response(UniversalBaseModel):
    id: str
    organization_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="organizationId"), pydantic.Field(alias="organizationId")
    ]
    status: ServiceStreamV1ResponseStatus
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]
    service_type: typing_extensions.Annotated[
        ServiceStreamV1ResponseServiceType, FieldMetadata(alias="serviceType"), pydantic.Field(alias="serviceType")
    ]
    date_of_service: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="dateOfService"), pydantic.Field(alias="dateOfService")
    ]
    external_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="externalId"), pydantic.Field(alias="externalId")
    ] = None
    patient_id: typing_extensions.Annotated[str, FieldMetadata(alias="patientId"), pydantic.Field(alias="patientId")]
    location: ServiceStreamV1ResponseLocation = pydantic.Field()
    """
    Location of the Patient at the date of service, requires only the `state` value for telehealth
    """

    note_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="noteId"), pydantic.Field(alias="noteId")
    ] = None
    service_eligibility: typing_extensions.Annotated[
        ServiceStreamV1ResponseServiceEligibility,
        FieldMetadata(alias="serviceEligibility"),
        pydantic.Field(alias="serviceEligibility"),
    ]
    coverage_status: typing_extensions.Annotated[
        ServiceStreamV1ResponseCoverageStatus,
        FieldMetadata(alias="coverageStatus"),
        pydantic.Field(alias="coverageStatus"),
    ]
    provider: ServiceStreamV1ResponseProvider
    payments: typing.List[ServiceStreamV1ResponsePayment]
    responsible_party: typing_extensions.Annotated[
        ServiceStreamV1ResponseResponsibleParty,
        FieldMetadata(alias="responsibleParty"),
        pydantic.Field(alias="responsibleParty"),
    ]
    patient_responsibility: typing_extensions.Annotated[
        ServiceStreamV1ResponsePatientResponsibility,
        FieldMetadata(alias="patientResponsibility"),
        pydantic.Field(alias="patientResponsibility"),
    ]
    tasks: typing.List[ServiceStreamV1ResponseTask]
    claim_status: typing_extensions.Annotated[
        typing.Optional[ServiceStreamV1ResponseClaimStatus],
        FieldMetadata(alias="claimStatus"),
        pydantic.Field(alias="claimStatus"),
    ] = None
    prior_authorization_number: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="priorAuthorizationNumber"),
        pydantic.Field(alias="priorAuthorizationNumber"),
    ] = None
    cancellation_reason: typing_extensions.Annotated[
        typing.Optional[ServiceStreamV1ResponseCancellationReason],
        FieldMetadata(alias="cancellationReason"),
        pydantic.Field(alias="cancellationReason"),
    ] = None
    metadata: typing.Optional[ServiceStreamV1ResponseMetadata] = pydantic.Field(default=None)
    """
    Customizable object of string to string key-value data
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
