# This file was auto-generated by Fern from our API Definition.

import typing

ServiceCreateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType = typing.Union[
    typing.Literal["UNKNOWN", "UNLIMITED", "LIMITED"], typing.Any
]
