# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .service_get_v_1_response_service_eligibility_field_conditional_patient_responsibilities_element_limit_field_metric import (
    ServiceGetV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldMetric,
)
from .service_get_v_1_response_service_eligibility_field_conditional_patient_responsibilities_element_limit_field_period import (
    ServiceGetV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod,
)
from .service_get_v_1_response_service_eligibility_field_conditional_patient_responsibilities_element_limit_field_type import (
    ServiceGetV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType,
)
from .service_get_v_1_response_service_eligibility_field_conditional_patient_responsibilities_element_limit_field_units import (
    ServiceGetV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldUnits,
)


class ServiceGetV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimit(UniversalBaseModel):
    type: ServiceGetV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType
    value: typing.Optional[int] = None
    metric: typing.Optional[
        ServiceGetV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldMetric
    ] = None
    period: typing.Optional[
        ServiceGetV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod
    ] = None
    units: typing.Optional[
        ServiceGetV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldUnits
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
