# This file was auto-generated by Fern from our API Definition.

import typing

ServicesListV1ResponseItemServiceEligibilityFieldPatientResponsibilityFieldDeductibleType = typing.Union[
    typing.Literal["INDIVIDUAL", "FAMILY"], typing.Any
]
