# This file was auto-generated by Fern from our API Definition.

import typing

ServiceStreamV1ResponseClaimStatus = typing.Union[
    typing.Literal["CREATED", "IN_PROGRESS", "PAID", "DENIED"], typing.Any
]
