# This file was auto-generated by Fern from our API Definition.

import typing

ServiceEligibilityGetV1ResponseStatus = typing.Union[
    typing.Literal["PENDING", "UNINSURED", "ELIGIBLE", "INELIGIBLE", "INEFFECTIVE"], typing.Any
]
