# This file was auto-generated by Fern from our API Definition.

import typing

ServiceEligibilityGetV1ResponseConditionalPatientResponsibilitiesElementPatientResponsibilityFieldDeductibleType = (
    typing.Union[typing.Literal["INDIVIDUAL", "FAMILY"], typing.Any]
)
