# This file was auto-generated by Fern from our API Definition.

import typing

ServiceEligibilityGetV1ResponsePatientResponsibilityFieldDeductibleType = typing.Union[
    typing.Literal["INDIVIDUAL", "FAMILY"], typing.Any
]
