# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from .raw_client import AsyncRawPaymentsClient, RawPaymentsClient
from .types.service_payments_list_v_1_response import ServicePaymentsListV1Response


class PaymentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPaymentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPaymentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPaymentsClient
        """
        return self._raw_client

    def list_service_payments(
        self,
        id: str,
        *,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ServicePaymentsListV1Response:
        """
        Parameters
        ----------
        id : str

        page : typing.Optional[int]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ServicePaymentsListV1Response

        Examples
        --------
        from rtaylor_205 import BridgeApiClient

        client = BridgeApiClient(
            api_key="YOUR_API_KEY",
        )
        client.services.payments.list_service_payments(
            id="id",
        )
        """
        _response = self._raw_client.list_service_payments(id, page=page, limit=limit, request_options=request_options)
        return _response.data


class AsyncPaymentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPaymentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPaymentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPaymentsClient
        """
        return self._raw_client

    async def list_service_payments(
        self,
        id: str,
        *,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ServicePaymentsListV1Response:
        """
        Parameters
        ----------
        id : str

        page : typing.Optional[int]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ServicePaymentsListV1Response

        Examples
        --------
        import asyncio

        from rtaylor_205 import AsyncBridgeApiClient

        client = AsyncBridgeApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.services.payments.list_service_payments(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_service_payments(
            id, page=page, limit=limit, request_options=request_options
        )
        return _response.data
