# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawPayersClient, RawPayersClient
from .types.payer_get_v_1_response import PayerGetV1Response


class PayersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPayersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPayersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPayersClient
        """
        return self._raw_client

    def get_payer(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> PayerGetV1Response:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PayerGetV1Response

        Examples
        --------
        from rtaylor_205 import BridgeApiClient

        client = BridgeApiClient(
            api_key="YOUR_API_KEY",
        )
        client.payers.get_payer(
            id="id",
        )
        """
        _response = self._raw_client.get_payer(id, request_options=request_options)
        return _response.data


class AsyncPayersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPayersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPayersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPayersClient
        """
        return self._raw_client

    async def get_payer(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PayerGetV1Response:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PayerGetV1Response

        Examples
        --------
        import asyncio

        from rtaylor_205 import AsyncBridgeApiClient

        client = AsyncBridgeApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.payers.get_payer(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_payer(id, request_options=request_options)
        return _response.data
