# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .search_payer_v_1_request import SearchPayerV1Request
    from .search_payer_v_1_response import SearchPayerV1Response
    from .search_payer_v_1_response_item import SearchPayerV1ResponseItem
_dynamic_imports: typing.Dict[str, str] = {
    "SearchPayerV1Request": ".search_payer_v_1_request",
    "SearchPayerV1Response": ".search_payer_v_1_response",
    "SearchPayerV1ResponseItem": ".search_payer_v_1_response_item",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = ["SearchPayerV1Request", "SearchPayerV1Response", "SearchPayerV1ResponseItem"]
