# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from .raw_client import AsyncRawV2Client, RawV2Client
from .types.service_cancel_v_2_request_cancellation_reason import ServiceCancelV2RequestCancellationReason
from .types.service_cancel_v_2_response import ServiceCancelV2Response
from .types.service_create_v_2_request_location import ServiceCreateV2RequestLocation
from .types.service_create_v_2_request_metadata import ServiceCreateV2RequestMetadata
from .types.service_create_v_2_request_responsible_party import ServiceCreateV2RequestResponsibleParty
from .types.service_create_v_2_request_service_eligibility import ServiceCreateV2RequestServiceEligibility
from .types.service_create_v_2_response import ServiceCreateV2Response
from .types.service_update_v_2_request_location import ServiceUpdateV2RequestLocation
from .types.service_update_v_2_request_metadata import ServiceUpdateV2RequestMetadata
from .types.service_update_v_2_request_responsible_party import ServiceUpdateV2RequestResponsibleParty
from .types.service_update_v_2_response import ServiceUpdateV2Response

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class V2Client:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawV2Client(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawV2Client:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawV2Client
        """
        return self._raw_client

    def create_service(
        self,
        *,
        patient_id: str,
        date_of_service: dt.datetime,
        service_type_id: str,
        location: ServiceCreateV2RequestLocation,
        provider_id: str,
        external_id: typing.Optional[str] = OMIT,
        service_eligibility: typing.Optional[ServiceCreateV2RequestServiceEligibility] = OMIT,
        prior_authorization_number: typing.Optional[str] = OMIT,
        metadata: typing.Optional[ServiceCreateV2RequestMetadata] = OMIT,
        responsible_party: typing.Optional[ServiceCreateV2RequestResponsibleParty] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ServiceCreateV2Response:
        """
        Creates a new `Service`, creates the `ServiceEligibility` in status `PENDING`

        Parameters
        ----------
        patient_id : str

        date_of_service : dt.datetime
            Full ISO8601 timestamp, including timezone

        service_type_id : str

        location : ServiceCreateV2RequestLocation
            Location of the Patient at the date of service, requires only the `state` value for telehealth

        provider_id : str

        external_id : typing.Optional[str]

        service_eligibility : typing.Optional[ServiceCreateV2RequestServiceEligibility]

        prior_authorization_number : typing.Optional[str]

        metadata : typing.Optional[ServiceCreateV2RequestMetadata]
            Customizable object of string to string key-value data

        responsible_party : typing.Optional[ServiceCreateV2RequestResponsibleParty]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ServiceCreateV2Response

        Examples
        --------
        import datetime

        from usebridge_api import BridgeApiClient
        from usebridge_api.services.v_2 import ServiceCreateV2RequestLocation

        client = BridgeApiClient(
            api_key="YOUR_API_KEY",
        )
        client.services.v_2.create_service(
            patient_id="patientId",
            date_of_service=datetime.datetime.fromisoformat(
                "2024-01-15 09:30:00+00:00",
            ),
            service_type_id="serviceTypeId",
            location=ServiceCreateV2RequestLocation(
                state="AL",
            ),
            provider_id="providerId",
        )
        """
        _response = self._raw_client.create_service(
            patient_id=patient_id,
            date_of_service=date_of_service,
            service_type_id=service_type_id,
            location=location,
            provider_id=provider_id,
            external_id=external_id,
            service_eligibility=service_eligibility,
            prior_authorization_number=prior_authorization_number,
            metadata=metadata,
            responsible_party=responsible_party,
            request_options=request_options,
        )
        return _response.data

    def cancel_service(
        self,
        id: str,
        *,
        cancellation_reason: typing.Optional[ServiceCancelV2RequestCancellationReason] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ServiceCancelV2Response:
        """
        Parameters
        ----------
        id : str

        cancellation_reason : typing.Optional[ServiceCancelV2RequestCancellationReason]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ServiceCancelV2Response

        Examples
        --------
        from usebridge_api import BridgeApiClient

        client = BridgeApiClient(
            api_key="YOUR_API_KEY",
        )
        client.services.v_2.cancel_service(
            id="id",
        )
        """
        _response = self._raw_client.cancel_service(
            id, cancellation_reason=cancellation_reason, request_options=request_options
        )
        return _response.data

    def update_service(
        self,
        id: str,
        *,
        patient_token: typing.Optional[str] = OMIT,
        date_of_service: typing.Optional[dt.datetime] = OMIT,
        service_type_id: typing.Optional[str] = OMIT,
        location: typing.Optional[ServiceUpdateV2RequestLocation] = OMIT,
        external_id: typing.Optional[str] = OMIT,
        provider_id: typing.Optional[str] = OMIT,
        prior_authorization_number: typing.Optional[str] = OMIT,
        responsible_party: typing.Optional[ServiceUpdateV2RequestResponsibleParty] = OMIT,
        metadata: typing.Optional[ServiceUpdateV2RequestMetadata] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ServiceUpdateV2Response:
        """
        Updates an existing `Service`

        Parameters
        ----------
        id : str

        patient_token : typing.Optional[str]

        date_of_service : typing.Optional[dt.datetime]
            Full ISO8601 timestamp, including timezone

        service_type_id : typing.Optional[str]

        location : typing.Optional[ServiceUpdateV2RequestLocation]
            Location of the Patient at the date of service, requires only the `state` value for telehealth

        external_id : typing.Optional[str]

        provider_id : typing.Optional[str]

        prior_authorization_number : typing.Optional[str]

        responsible_party : typing.Optional[ServiceUpdateV2RequestResponsibleParty]

        metadata : typing.Optional[ServiceUpdateV2RequestMetadata]
            Customizable object of string to string key-value data<br>Any modifications to this field will _overwrite_ the previous value

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ServiceUpdateV2Response

        Examples
        --------
        from usebridge_api import BridgeApiClient

        client = BridgeApiClient(
            api_key="YOUR_API_KEY",
        )
        client.services.v_2.update_service(
            id="id",
        )
        """
        _response = self._raw_client.update_service(
            id,
            patient_token=patient_token,
            date_of_service=date_of_service,
            service_type_id=service_type_id,
            location=location,
            external_id=external_id,
            provider_id=provider_id,
            prior_authorization_number=prior_authorization_number,
            responsible_party=responsible_party,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data


class AsyncV2Client:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawV2Client(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawV2Client:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawV2Client
        """
        return self._raw_client

    async def create_service(
        self,
        *,
        patient_id: str,
        date_of_service: dt.datetime,
        service_type_id: str,
        location: ServiceCreateV2RequestLocation,
        provider_id: str,
        external_id: typing.Optional[str] = OMIT,
        service_eligibility: typing.Optional[ServiceCreateV2RequestServiceEligibility] = OMIT,
        prior_authorization_number: typing.Optional[str] = OMIT,
        metadata: typing.Optional[ServiceCreateV2RequestMetadata] = OMIT,
        responsible_party: typing.Optional[ServiceCreateV2RequestResponsibleParty] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ServiceCreateV2Response:
        """
        Creates a new `Service`, creates the `ServiceEligibility` in status `PENDING`

        Parameters
        ----------
        patient_id : str

        date_of_service : dt.datetime
            Full ISO8601 timestamp, including timezone

        service_type_id : str

        location : ServiceCreateV2RequestLocation
            Location of the Patient at the date of service, requires only the `state` value for telehealth

        provider_id : str

        external_id : typing.Optional[str]

        service_eligibility : typing.Optional[ServiceCreateV2RequestServiceEligibility]

        prior_authorization_number : typing.Optional[str]

        metadata : typing.Optional[ServiceCreateV2RequestMetadata]
            Customizable object of string to string key-value data

        responsible_party : typing.Optional[ServiceCreateV2RequestResponsibleParty]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ServiceCreateV2Response

        Examples
        --------
        import asyncio
        import datetime

        from usebridge_api import AsyncBridgeApiClient
        from usebridge_api.services.v_2 import ServiceCreateV2RequestLocation

        client = AsyncBridgeApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.services.v_2.create_service(
                patient_id="patientId",
                date_of_service=datetime.datetime.fromisoformat(
                    "2024-01-15 09:30:00+00:00",
                ),
                service_type_id="serviceTypeId",
                location=ServiceCreateV2RequestLocation(
                    state="AL",
                ),
                provider_id="providerId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_service(
            patient_id=patient_id,
            date_of_service=date_of_service,
            service_type_id=service_type_id,
            location=location,
            provider_id=provider_id,
            external_id=external_id,
            service_eligibility=service_eligibility,
            prior_authorization_number=prior_authorization_number,
            metadata=metadata,
            responsible_party=responsible_party,
            request_options=request_options,
        )
        return _response.data

    async def cancel_service(
        self,
        id: str,
        *,
        cancellation_reason: typing.Optional[ServiceCancelV2RequestCancellationReason] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ServiceCancelV2Response:
        """
        Parameters
        ----------
        id : str

        cancellation_reason : typing.Optional[ServiceCancelV2RequestCancellationReason]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ServiceCancelV2Response

        Examples
        --------
        import asyncio

        from usebridge_api import AsyncBridgeApiClient

        client = AsyncBridgeApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.services.v_2.cancel_service(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cancel_service(
            id, cancellation_reason=cancellation_reason, request_options=request_options
        )
        return _response.data

    async def update_service(
        self,
        id: str,
        *,
        patient_token: typing.Optional[str] = OMIT,
        date_of_service: typing.Optional[dt.datetime] = OMIT,
        service_type_id: typing.Optional[str] = OMIT,
        location: typing.Optional[ServiceUpdateV2RequestLocation] = OMIT,
        external_id: typing.Optional[str] = OMIT,
        provider_id: typing.Optional[str] = OMIT,
        prior_authorization_number: typing.Optional[str] = OMIT,
        responsible_party: typing.Optional[ServiceUpdateV2RequestResponsibleParty] = OMIT,
        metadata: typing.Optional[ServiceUpdateV2RequestMetadata] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ServiceUpdateV2Response:
        """
        Updates an existing `Service`

        Parameters
        ----------
        id : str

        patient_token : typing.Optional[str]

        date_of_service : typing.Optional[dt.datetime]
            Full ISO8601 timestamp, including timezone

        service_type_id : typing.Optional[str]

        location : typing.Optional[ServiceUpdateV2RequestLocation]
            Location of the Patient at the date of service, requires only the `state` value for telehealth

        external_id : typing.Optional[str]

        provider_id : typing.Optional[str]

        prior_authorization_number : typing.Optional[str]

        responsible_party : typing.Optional[ServiceUpdateV2RequestResponsibleParty]

        metadata : typing.Optional[ServiceUpdateV2RequestMetadata]
            Customizable object of string to string key-value data<br>Any modifications to this field will _overwrite_ the previous value

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ServiceUpdateV2Response

        Examples
        --------
        import asyncio

        from usebridge_api import AsyncBridgeApiClient

        client = AsyncBridgeApiClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.services.v_2.update_service(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_service(
            id,
            patient_token=patient_token,
            date_of_service=date_of_service,
            service_type_id=service_type_id,
            location=location,
            external_id=external_id,
            provider_id=provider_id,
            prior_authorization_number=prior_authorization_number,
            responsible_party=responsible_party,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data
